### ISSUE TITLE
Representations - kernel_methods : Undefined name `metric`

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#1033]
In `_sklearn_wrapper(metric, **kwargs)`, `metric` is undefined, cf.

https://github.com/GUDHI/gudhi-devel/blob/06bc78ae0a3d96d1273e37438cfd1f116118385a/src/python/gudhi/representations/kernel_methods.py#L89

**Comment by MathieuCarriere** [comment]
Yes good catch it should be `kernel` instead I think

**Comment by MathieuCarriere** [comment]
Just created PR #1037
