### ISSUE TITLE
Periodic alpha complex with DTM filtration

### ISSUE THREAD

**Issue by Lxion0553** [GUDHI/gudhi-devel#1041]
Hi!

I'm trying to alpha complex with DTM filtration in periodic box. I saw that there are DTM codes in the python interface, but I didn't find  
similar things in the c++ library (probably). While the python interface doesn't have periodic alpha complex implantation. Is there an relatively easy way to construct periodic alpha complex with DTM filtration in python (or c++)?

Thanks a lot!

**Comment by mglisse** [comment]
Hello,
if I understand correctly, you want to build an alpha-complex, in a periodic space, using as weights (as in a regular triangulation) the DTM at each vertex? You are going to need to code some pieces yourself to get the complete pipeline.
- computing the DTM: essentially, for each point, you need to find the distances to the k nearest neighbors (in the periodic metric). I would first try it brute-force (compute the distances to all the other points, then `std::nth_element`), and if that's too slow, I would look into using `CGAL::Kd_tree` with a custom query item (and possibly custom traits).
- compute the alpha-complex. If your data is in 3d, you can use Gudhi's Alpha_complex_3d (C++). In 2d, I think you can use CGAL, but extracting the filtration from Alpha_shape_2 is non-trivial. In other dimensions, you are out of luck.

**Comment by Lxion0553** [comment]
Thanks for your guide! 
It seems like I should construct periodic alpha complex first and then compute DTM value for each vertex and filtration value for each edge and add vertices and edges with corresponding filtration value to simplex tree?

**Comment by Lxion0553** [comment]
I understand. Thanks!
