### ISSUE TITLE
Cannot have 2 threads that both compute persistence on completely independent filtrations.

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#1082]
It seems like a big problem if we cannot even have 2 threads that both compute persistence on completely independent filtrations.

_Originally posted by @mglisse in https://github.com/GUDHI/gudhi-devel/pull/669#discussion_r1649558063_

**Comment by hschreiber** [comment]
> Ah, I forgot about that. I think, we can just remove the `static` from it and it should work just fine as it is only used inside the compressed matrix.

Should I do it?
