### ISSUE TITLE
[python - persistence_graphical tools] Dimension 1 color in the palette is not visible with video projector

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#109]
For persistence diagram and bar code, the dimension 1 color in the palette (a light green) is not distinguishable when projecting the video on a white screen

**Comment by mglisse** [comment]
Aren't we using the default from matplotlib? Has this been reported to them?

**Comment by VincentRouvreau** [comment]
> Aren't we using the default from matplotlib? Has this been reported to them?

No. I defined the palette, but it was not a good idea. Matplotlib has its own palette (even used by bokeh).

**Comment by VincentRouvreau** [comment]
Fixed by #119
