### ISSUE TITLE
[python] replace "is" with "=="

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#113]
`if max_plots is not 1000` looks wrong, I think we want `!=`. I am getting "Deprecated parameter. It has been replaced by max_intervals" for every call to the graphical tools.
```
>>> a=1000
>>> a is 1000
False
>>> a==1000
True
```

**Comment by mglisse** [comment]
Python 3.8 shows
> SyntaxWarning: "is" with a literal. Did you mean "=="?

:+1:

**Comment by VincentRouvreau** [comment]
Fixed by #137 and #119
