### ISSUE TITLE
Use relative path for sources in setup.py

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#1130]
https://setuptools.pypa.io/en/latest/userguide/ext_modules.html#extension-api-reference says about the parameters of `setuptools.Extension`
> sources (list[str]) – list of source filenames, **relative** to the distribution root (where the setup script lives), in Unix form (slash-separated) for portability.

However, we have in setup.py.in `sources = [source_dir + module + '.pyx',],` where `source_dir='@CMAKE_CURRENT_SOURCE_DIR@/gudhi/'`, i.e. an absolute path.

While this has been working so far, it seems to be the cause (one of the causes) of our current difficulties building for python 3.13 on windows on conda-forge.

(relevant ref: https://github.com/pypa/setuptools/issues/4645)

**Comment by VincentRouvreau** [comment]
I gave a try to a relative one: `source_dir='../../../src/python/gudhi'`, but:
```
gcc -pthread -B /miniconda/envs/gudhi-devel/compiler_compat -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /miniconda/envs/gudhi-devel/include -fPIC -O2 -isystem /miniconda/envs/gudhi-devel/include -fPIC -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -I/miniconda/envs/gudhi-devel/lib/python3.11/site-packages/numpy/core/include -I/workspace/gudhi/gudhi-devel/src/python/gudhi/ -I/miniconda/envs/gudhi-devel/include/eigen3 -I/workspace/gudhi/gudhi-devel/ext/hera/include -I/miniconda/envs/gudhi-devel/include -I/workspace/gudhi/gudhi-devel/src/common/include -I/workspace/gudhi/gudhi-devel/src/Alpha_complex/include -I/workspace/gudhi/gudhi-devel/src/Bitmap_cubical_complex/include -I/workspace/gudhi/gudhi-devel/src/Bottleneck_distance/include -I/workspace/gudhi/gudhi-devel/src/Collapse/include -I/workspace/gudhi/gudhi-devel/src/Contraction/include -I/workspace/gudhi/gudhi-devel/src/Coxeter_triangulation/include -I/workspace/gudhi/gudhi-devel/src/Cech_complex/include -I/workspace/gudhi/gudhi-devel/src/Hasse_complex/include -I/workspace/gudhi/gudhi-devel/src/Persistence_representations/include -I/workspace/gudhi/gudhi-devel/src/Persistent_cohomology/include -I/workspace/gudhi/gudhi-devel/src/Rips_complex/include -I/workspace/gudhi/gudhi-devel/src/Simplex_tree/include -I/workspace/gudhi/gudhi-devel/src/Skeleton_blocker/include -I/workspace/gudhi/gudhi-devel/src/Spatial_searching/include -I/workspace/gudhi/gudhi-devel/src/Subsampling/include -I/workspace/gudhi/gudhi-devel/src/Tangential_complex/include -I/workspace/gudhi/gudhi-devel/src/Toplex_map/include -I/workspace/gudhi/gudhi-devel/src/Witness_complex/include -I/workspace/gudhi/gudhi-devel/src/Nerve_GIC/include -I/workspace/gudhi/gudhi-devel/src/Persistence_matrix/include -I/workspace/gudhi/gudhi-devel/src/python/include -I/miniconda/envs/gudhi-devel/include/python3.11 -c ../../../src/python/gudhi/off_utils.cpp -o build/temp.linux-x86_64-cpython-311/../../../src/python/gudhi/off_utils.o -DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_ALL_NO_LIB -DBOOST_SYSTEM_NO_DEPRECATED -std=c++17 -frounding-math -DCGAL_EIGEN3_ENABLED -DCGAL_HEADER_ONLY -DCGAL_USE_GMP -DCGAL_USE_GMPXX -DCGAL_USE_MPFR
Assembler messages:
Fatal error: can't create build/temp.linux-x86_64-cpython-311/../../../src/python/gudhi/off_utils.o: No such file or directory
```

`source_dir` is waiting for a relative path but doesn't `../`. I do not see how we could workaround this new behaviour.

**Comment by mglisse** [comment]
> ```
> Fatal error: can't create build/temp.linux-x86_64-cpython-311/../../../src/python/gudhi/off_utils.o: No such file or directory
> ```

:disappointed: so much for the easy way.

> I do not see how we could workaround

Apparently they want the sources and setup.py in the same place. Some possibilities would be
* move the generated setup.py next to the sources
* copy the sources next to setup.py
* create a (sym)link to the source dir in the build dir
* :trollface: completely rewrite the build system without setuptools

> this new behaviour.

Supposedly what we were doing was never supported. We can keep our fingers crossed that they will "fix" the recent regression, but they don't promise that it won't break again.

**Comment by VincentRouvreau** [comment]
I gave a [try to symbolic links](https://github.com/VincentRouvreau/play_with_azure_pipelines/commit/d97d375f4b0f9ee2ee1e5cfac809e3c5a85677c1) and it seems to work nicely on windows, osx and linux. CMake 3.14 is required, but `cmake_minimum_required` is already 3.15.
