### ISSUE TITLE
Kernel dies while computing persistence

### ISSUE THREAD

**Issue by MarioAuditore** [GUDHI/gudhi-devel#1141]
I tried to play around with covariance matrices from geomstats:

```python
import gudhi as gd  
import geomstats.datasets.utils as data_utils

data, patient_ids, labels = data_utils.load_connectomes()

dgm = gd.RipsComplex(
    distance_matrix = data[0],
    max_edge_length = 1.0
).create_simplex_tree(max_dimension = 2)

dgm.compute_persistence()
```
However this code just instantly kills the jupyter kernel.
Python 3.11.4 on MacOS, M1 pro

**Comment by mglisse** [comment]
Indeed. The code will only look at the (strict) lower triangular matrix, but you have negative values in this matrix, so we end up with edges that have a filtration value smaller than that of the vertices (0), which violates the definition of a filtration.
We could add some tests to avoid crashing the Python interpreter. Testing if a SimplexTree is a proper filtration may be a bit expensive though.
