### ISSUE TITLE
How can get the key of simplex in Simplex Tree in GUDHI python?

### ISSUE THREAD

**Issue by ScarletVV** [GUDHI/gudhi-devel#1144]
If I have a simplex such as [0, 1, 2], a triangle, how can I get the key(N) of this triangle in Simplex Tree, so I will know the triangle is Nth simplex add to simplicial complexes, and can I use the key to get the simplex ([0, 1, 2)]？

**Comment by mglisse** [comment]
This functionality is available in C++ (https://gudhi.inria.fr/doc/3.10.1/class_gudhi_1_1_simplex__tree.html#a39fde6b8f9c1a47e02c3b82b0062f588 and https://gudhi.inria.fr/doc/3.10.1/class_gudhi_1_1_simplex__tree.html#a872198e2a65c71d7843b3cc329a8060e), but we have not made it available in Python so far. One reason is that using it can be error-prone: computing persistence overwrites a number of keys, modifying the complex (say adding a simplex) invalidates the filtration order and it is not automatically recomputed (too costly), etc.

Could you tell us more about your use case?

**Comment by ScarletVV** [comment]
Thank you for your reply and detailed explanation! I did it in C++. Since much of my analysis code relies on Python packages, I need to consider combining C++ and Python programming. Your work is excellent, and if possible, I hope to utilize this functionality in Python as well. Best wishes to all of you!
