### ISSUE TITLE
[cython] Use `except +`

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#116]
For instance, in rips_complex.py, one can write:
```diff
-void create_simplex_tree(Simplex_tree_interface_full_featured* simplex_tree, int dim_max)
+void create_simplex_tree(Simplex_tree_interface_full_featured* simplex_tree, int dim_max) except +
```
so that when there isn't enough memory, the C++ bad_alloc exception is turned into a python exception instead of crashing the whole python process.

**Comment by mglisse** [comment]
There are probably a number of other places where we could add `except +`, but I guess we don't need an issue for that, if it doesn't contain any specific pointers to places where it is missing.

**Comment by VincentRouvreau** [comment]
> There are probably a number of other places where we could add `except +`, but I guess we don't need an issue for that, if it doesn't contain any specific pointers to places where it is missing.

Do you want to keep it open ?

**Comment by mglisse** [comment]
Nah, we can reopen it when we find a specific place where we should add `except +`.
