### ISSUE TITLE
[python - CMake] Plugins not linked with TBB in Debug mode

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#117]
I configured gudhi with `-DCMAKE_BUILD_TYPE=Debug` on linux. This resulted in a broken python plugin, because TBB is enabled but not linked. Release mode works fine (it has `-ltbb -ltbb_malloc` which are missing in Debug). Looking at CMakeCache.txt, I see:
> TBB_DEBUG_LIBRARY:FILEPATH=TBB_DEBUG_LIBRARY-NOTFOUND
> TBB_RELEASE_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libtbb.so
> TBB_LIBRARIES:PATH=optimized;/usr/lib/x86_64-linux-gnu/libtbb.so;debug;/usr/lib/x86_64-linux-gnu/libtbb.so;optimized;/usr/lib/x86_64-linux-gnu/libtbbmalloc.so;debug;/usr/lib/x86_64-linux-gnu/libtbbmalloc.so;general;-pthread

while we are blindly using `TBB_DEBUG_LIBRARY`.

**Comment by VincentRouvreau** [comment]
According to this [stack post](https://stackoverflow.com/a/38983037/5092461), we should do something like:
```
target_link_libraries ( app
    debug ${Boost_FILESYSTEM_LIBRARY_DEBUG}
    optimized ${Boost_FILESYSTEM_LIBRARY_RELEASE} )

target_link_libraries ( app
    debug ${Boost_LOG_LIBRARY_DEBUG}
    optimized ${Boost_LOG_LIBRARY_RELEASE} )

target_link_libraries ( app
    debug ${Boost_PROGRAM_OPTIONS_LIBRARY_DEBUG}
    optimized ${Boost_PROGRAM_OPTIONS_LIBRARY_RELEASE} )
```
The same for all third parties libraries.
Maybe more difficult to be done on Python part.

**Comment by Hind-M** [comment]
Hum, if you install TBB with apt-get you won't have the corresponding debug libs (this is my case anyway): https://packages.ubuntu.com/focal/amd64/libtbb-dev/filelist. But, it seems that they are available if you install from TBB sources: https://github.com/oneapi-src/oneTBB/releases. I am not sure if people do that...
Should we just use:
```
add_GUDHI_PYTHON_lib("${TBB_RELEASE_LIBRARY}")
add_GUDHI_PYTHON_lib("${TBB_MALLOC_RELEASE_LIBRARY}")
```
even in Debug mode in Python CMakeLists.txt? (maybe after checking that `TBB_DEBUG_LIBRARY` is not found)
It won't generate the debug info (but that depends on how TBB is installed anyway) but at least it would prevent python tests from failing...

**Comment by mglisse** [comment]
IIUC, windows / visual studio has several incompatible ABIs (release vs debug, multi-thread vs single-thread, etc), so it needs multiple libraries. But that's not at all a generality. On linux, there is mostly just one ABI, so you can always link with the same version of TBB, however you compile your code.

**Comment by Hind-M** [comment]
Ok, but then the provided libtbb-dev package still has no debug lib file for tbb... According to this [issue](https://github.com/flann-lib/flann/issues/52), we should use the tbb release version even in debugging unless we want to debug tbb itself...

**Comment by mglisse** [comment]
> According to this [issue](https://github.com/flann-lib/flann/issues/52), we should use the tbb release version even in debugging unless we want to debug tbb itself...

Yes, that's what I was saying. On linux, it is all ABI compatible, whereas on windows "debug" is the name of a different ABI. Note that it can still be nice to install libtbb2-dbgsym to get the symbols so that a debugger can print nicer information, if you run a debugger or profiler or similar (unless you have configured debuginfod to download it on demand).
