### ISSUE TITLE
[Python] `std::bad_alloc` thrown we running `betti_numbers()`

### ISSUE THREAD

**Issue by jjerphan** [GUDHI/gudhi-devel#122]
Hello,

When I run this simple snippet in Python:
```python
In [1]: import numpy as np
   ...: import gudhi as gd
   ...: import random as rd
   ...: import matplotlib.pyplot as plt
   ...: 

In [2]: st = gd.SimplexTree()
   ...: st.initialize_filtration()
   ...: st.persistence()
   ...: 
Out[2]: []

In [3]: st.betti_numbers()
```
I get a bad allocation in the C++ back-end:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[1]    30948 abort (core dumped)  ipython
```

Is there a debug it easily?

Thank you!

**Comment by mglisse** [comment]
When the complex is empty, `dim_max_` is -1, and we should not try to allocate a vector of size -1. I think we should allocate a vector of size `dim_max_+1` when the complex is empty or `persistence_dim_max` is true.
