### ISSUE TITLE
Serialize / pickle simplex trees

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#132]
Currently, if I want to save a simplex tree so I can reload it later, I can use get_filtration and pickle that, and to reload I have to do a bunch of insertions. For large complexes, this is costly, both in time and in space, although we could start with that. A more efficient way would probably involve something like Boost.Serialization in C++, and a suitable wrapper in python.

**Comment by VincentRouvreau** [comment]
@mglisse Would Boost.Serialization add some values ? Compared to `operator<<` and `operator>>` that are already available in C++ for the simplex tree ? (maybe some file compression mechanism, I did not check)

**Comment by mglisse** [comment]
Implemented by #810.
