### ISSUE TITLE
[Nerve_GIC] CGAL dependency check

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#142]
https://github.com/GUDHI/gudhi-devel/blob/184587947b18daf57583c7cb111ad315b8d48a43/src/Nerve_GIC/include/gudhi/GIC.h#L53

The error message is confusing, is it supposed to say Bottleneck instead of Alpha_complex_3d? Or Cover_complex?

The test in this file seems redundant. Nothing uses CGAL directly, and the dependencies that do use CGAL (Bottleneck.h) already have such a check.

If bottleneck is the only thing that leads to a CGAL dependency in this file (is it?), I believe it should be possible to disable just a few related functions (compute_distribution and the 3 that follow and depend on it) when CGAL is not available, and the rest would still be fine. Detection could be done either through the C++17 `__has_include` mechanism, or with a macro (GUDHI_NO_CGAL?) defined by cmake.

**Comment by VincentRouvreau** [comment]
Fixed on #154
