### ISSUE TITLE
[python representations] Deduplicate code

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#148]
There is some duplicated code in gudhi.representations. For instance, most classes in vector_methods seem to have the same `fit` method that computes `sample_range`. It should be moved to a single function. @martinroyer suggested a base class, I don't have a strong opinion on that.

**Comment by VincentRouvreau** [comment]
@mglisse It seems this has been fixed on #538 
I do not see any other `fit` to be factorized.
