### ISSUE TITLE
[python representations] Landscapes null entries

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#166]
When we do not specify the bounds for a landscape, it automatically picks the min and max of the births and deaths. This may be right for some other classes. But for landscapes, the value at min or at max is always 0, so this creates 2*num_landscapes coordinates that are always 0.

Some possibilities would be:
* pretend we asked for resolution+2, and drop the extremes
* use half-values: instead of "min, min+t, min+2*t, ..., max", use "min+t/2, min+3*t/2, ... max-t/2".

**Comment by MathieuCarriere** [comment]
Should be fixed in #173
