### ISSUE TITLE
[build] Python build scripts fail on multi-user setup

### ISSUE THREAD

**Issue by robindar** [GUDHI/gudhi-devel#175]
This issue arises when building Gudhi's python package from source, as indicated in [Gudhi's python instalation page](https://gudhi.inria.fr/python/latest/installation.html) on a multi-user setup.

In a multi-user setup, some python packages are installed system-wide
(with `pip install <pkg>`), and some packages are installed on a per-user basis, in their respective home directory (with `pip install --user <pkg>`). The latter does not require root privilieges and does not affect other user's installations. This is handled similarly by `setuptools` with the use of the `--user` flag, i.e. `python3 setup.py install --user`

When building Gudhi from source for python, the installation step (`make install`) calls setuptools without exposing an option / prompting for the multi-user setup. This can be fixed manually by running `python3 setup.py install --user` in `build/src/python` after the `make install` step failed when running `python3 setup.py install` without the `--user` flag (because root privileges are not given for system-wide installation and the `--user` flag is not passed to setuptools to indicate per-user installation), but could be handled nicely by make.

Side note: most python virtual environments break the rules of multi-user setups, and using the `--user` flag in such environments can break stuff in unexpected ways. I assume people using a mutli-user setup know about it, and handling every possible virtual environment manager would be too much work, so the easiest way to handle this is probably to leave the current install script as default, and only provide (and document) an additional flag to handle this multi-user case.

See [pip user-install section](https://pip.readthedocs.io/en/latest/user_guide/#user-installs) for further information on multi-user setups.

**Comment by mglisse** [comment]
Hello,
with #153, we decided that handling all cases in make would be too much, and we instead document the `python setup.py ***` commands so people can customize them with their favorite flags. We give the example
> python setup.py  install --prefix /home/gudhi  # Install in /home/gudhi directory

If that's not enough, we could add a similar 1-line example with `--user`.
Does that look good enough to you?

**Comment by robindar** [comment]
Congratulations on the impressive response time, this is some really fast triage !

I would say the documentation in `src/python/doc/installation.rst` is indeed sufficiently detailed. I'm sorry, I hadn't bothered to check the documentation sources before opening the issue, I just assumed the [online documentation](https://gudhi.inria.fr/python/latest/installation.html) was up to date.

If you can confirm that these changes will be reflected on the website, then I don't believe there's a need to add anything about the `--user` flag specifically.

**Comment by mglisse** [comment]
> I just assumed the [online documentation](https://gudhi.inria.fr/python/latest/installation.html) was up to date.

The online documentation is for the latest release. What you saw in master hasn't been released yet, but as soon as we release it (hopefully soon), the online doc will reflect it.
Thank you for reporting this issue, don't hesitate to report further trouble.
