### ISSUE TITLE
[Python] read_off name too general

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#194]
The C++ function `read_points_from_OFF_file` has a python wrapper named `read_off`. I think this name is too generic. OFF files are normally meant to encode meshes. A user seeing a function `read_off` would expect a mesh as output, possibly encoded as a SimplexTree because that's the only structure we have here. It is fine to use OFF just for their points, but we need to be explicit about it, as in C++.

**Comment by VincentRouvreau** [comment]
Do we ensure retro-compatibility or not ?
With a deprecated user warning, for instance.

**Comment by mglisse** [comment]
I don't know. I would certainly mention it in the release notes.
This function is not documented, but it is used in examples, so I don't know how likely it is that users have it in their code.
I think I would be ok just breaking it, but if you want to add something, that's ok too.
