### ISSUE TITLE
[Cython - simplex_tree] There is no simplex iterators

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#2]
We have to use get_filtration() to find the list of simplices.
There shall be an simplex iterator (cf.itertools)

**Comment by mglisse** [comment]
Let me add some details here. The simplex tree data structure was invented to save space. It has size n (number of simplices), while more common representations have size n*d (d is the dimension). If at any point we create a vector of vectors of vertices to represent all the simplices, we have killed the whole point of the simplex tree and should use a different complex instead (which we sadly do not have currently). However, creating such a vector is not necessary to iterate on the simplices. In C++, we have `Complex_simplex_range`/`Complex_simplex_iterator`, and the idea would be to interface that in python. Similarly, get_filtration could wrap iterators on the internal filtration vector, and only build the tuple (simplex, filtration_value) when the iteration reaches that element.
Then come the details, can this be implemented as a generator or does it need something more manual, etc.

**Comment by yagu0** [comment]
It seems that the "vector of vectors of vertices" is the current situation in the C++ functions get_filtration(), get_skeleton(), get_star() and get_cofaces(). So when Python get the result and build an iterator, it's already too late. I like the idea of directly interfacing a C++ iterator, I'll have a look in this direction.

**Comment by mglisse** [comment]
> It seems that the "vector of vectors of vertices" is the current situation in the C++ functions get_filtration(), get_skeleton(), get_star() and get_cofaces(). So when Python get the result and build an iterator, it's already too late.

Yes. We did it that way in the beginning because it was a quick and easy way to have the functionality, and haven't had time to revisit since then.

**Comment by VincentRouvreau** [comment]
When I wrote this issue, I was thinking resolving it by using `yield` on the simplex iterator. I am not sure if this is the correct way to do it, or even if it works, but it seems promising.
