### ISSUE TITLE
[sphinx] Shorter headers in sphinx summaries

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#248]
Sphinx, or the style we use, has a tendency to split "Introduced in" into 4 to 5 lines in the summary tables (it also has crazy vertical alignment, but that's a different issue). Ideally this should be improved, but to mitigate the issue, we could use shorter names. Some random possibilities (I am not saying we should use those):

Introduced in -> Since
Copyright -> ©, License
Author -> By
Requires -> Needs, Uses

**Comment by VincentRouvreau** [comment]
@mglisse
We could also let less space for the text description and more space for these columns:
https://3791-174304137-gh.circle-artifacts.com/0/tmp/sphinx/index.html

It is not easy as all is modified when you change of screen (phone, ipad, ...)

**Comment by mglisse** [comment]
>  We could also let less space for the text description and more space for these columns:

The 2 are not incompatible, we can do both :wink:
Reducing the width for the text description is a good way to remind people that they are not supposed to write their whole doc there, just 2-4 lines that go straight to the point so we know what it is about. :+1:

> It is not easy as all is modified when you change of screen (phone, ipad, ...)

The style is too eager to reduce the top-bar to a single hamburger, but never reduces the left side-bar with the TOC, so it isn't optimal. But it works well enough...

**Comment by VincentRouvreau** [comment]
I did not take all your proposals but the result seems great (to me):
https://3850-174304137-gh.circle-artifacts.com/0/tmp/sphinx/index.html

Introduced in -> Since
Copyright -> License

**Comment by mglisse** [comment]
It is a nice improvement, yes. Not perfect, especially with larger text, but good enough, thanks.
"Cubical complex user manual" looks strange, it makes the table with author, since, etc not as wide as it could be, which forces it to break into 2 lines, but that seems to be because of the CSS, so a separate problem.
