### ISSUE TITLE
[Bitmap_cubical_complex] compute_incidence_between_cells has inconsistent const

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#257]
> Bitmap_cubical_complex_base.h:  virtual int compute_incidence_between_cells(std::size_t coface, std::size_t face) **const** {

> Bitmap_cubical_complex_periodic_boundary_conditions_base.h:  virtual int compute_incidence_between_cells(std::size_t coface, std::size_t face) {

but virtual functions need signatures that exactly match, or they might as well not be virtual.

**Comment by VincentRouvreau** [comment]
Closed by #385
