### ISSUE TITLE
[CMake - TBB] TBB requires to link against libatomic on some non-x86_64 architectures

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#26]
Some non-x86_64 architectures seem to require explicitly linking against libatomic for the things that use TBB. I'm currently just adding it to the list of TBB libraries. Perhaps CMake can do something more intelligent on the architectures where it's needed?
https://git.nonempty.org/debian-gudhi/tree/debian/patches/0007-Force-linking-against-libatomic-for-parts-that-use-T.patch?h=debian/sid&id=fed62e52ab396f0d6ba9029f12d5ef35d7761989

**Comment by VincentRouvreau** [comment]
@gspr Is this issue still relevant ?
I checked in other `FindTBB.cmake` files like the one in [CGAL](https://github.com/CGAL/cgal/blob/master/Installation/cmake/modules/FindTBB.cmake) or [this one](https://github.com/justusc/FindTBB/blob/master/FindTBB.cmake) and they never link against `libatomic`.
I also checked [TBB release notes](https://software.intel.com/content/www/us/en/develop/articles/intel-threading-building-blocks-release-notes.html) and [TBB issue tracker](https://github.com/oneapi-src/oneTBB/issues?q=is%3Aissue+atomic) and it is not clear to me when we need to link against libatomic

**Comment by gspr** [comment]
Vincent Rouvreau <notifications@github.com> writes:

> @gspr Is this issue still relevant ?

No, it seems that this is no longer an issue.

I've removed the Debian patch for this for the 3.4.1 build, and things
seem to be working fine.

Thanks.

**Comment by VincentRouvreau** [comment]
Thanks for the test, I am closing it.
