### ISSUE TITLE
doxygen doc in the source directory

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#267]
In a user version, I create a subdirectory build, cd build, cmake ..., make doxygen, and find the documentation in ../doc/html, i.e. outside of the build directory.

**Comment by VincentRouvreau** [comment]
When you do cmake, do you precise any ` -DUSER_VERSION_DIR=...` ?
Because doxygen builds the documentation from the `user_version` make target in doc/html directory. In other words, documentation is built in `${USER_VERSION_DIR}/doc/html` directory.

**Comment by mglisse** [comment]
No, I didn't specify any USER_VERSION. I expected that by default, everything that gets built ends up in the build directory...
Should I consider user versions as throwaways and build things directly in place, without a separate build directory?
