### ISSUE TITLE
[python - persistence_graphical tools] It would be nice to accept list of tuple(birth, death) as input

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#27]
It would be nice to accept list of tuple(birth, death) as input and not only tuples(dimension, tuple(birth, death))

**Comment by mglisse** [comment]
List of tuple(birth,death) would actually more likely be numpy.array of shape (n,2). It becomes more complicated if we want to plot several dimensions, I don't think we have settled on a format for that, between list[array nx2], dict[dim, array nx2], etc. But already just handling one numpy.array of shape (n,2) would be nice.
