### ISSUE TITLE
[python - SimplexTree] boundary of a simplex

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#29]
We have python interfaces for the inefficient access to coboundaries (get_cofaces), but we seem to be missing access to the more natural boundaries...

**Comment by mglisse** [comment]
`itertools.combinations(s,len(s)-1)`

**Comment by VincentRouvreau** [comment]
@mglisse now that #362 is merged, do we keep this issue to show how to get boundaries in pure python ?

**Comment by mglisse** [comment]
If you want we can add to the documentation of the new function a sentence like
> If you do not need the filtration values, the boundary can also be obtained as `itertools.combinations(s,len(s)-1)`

but I don't think we need to keep this issue open.
