### ISSUE TITLE
Bug in CubicalComplex.cofaces_of_persistence_pairs() when the persistence diagram has no paired birth and death

### ISSUE THREAD

**Issue by jisuk1** [GUDHI/gudhi-devel#322]
Hello, I think I found a potential bug in CubicalComplex.cofaces_of_persistence_pairs() in src/python/gudhi/cubical_complex.pyx, when the persistence diagram has no paired birth and death, i.e. having only one feature that doesn't die:

When I try to run the following code,
cubCpx = gudhi.CubicalComplex(dimensions=[1,2], top_dimensional_cells=[0.0, 1.0])
Diag = cubCpx.persistence(homology_coeff_field=2, min_persistence=0)
pairs = cubCpx.cofaces_of_persistence_pairs()

It returns error like:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-5750e677edc0> in <module>()
      1 cubCpx = gudhi.CubicalComplex(dimensions=[1,2], top_dimensional_cells=[0.0, 1.0])
      2 Diag = cubCpx.persistence(homology_coeff_field=2, min_persistence=0)
----> 3 pairs = cubCpx.cofaces_of_persistence_pairs()

cubical_complex.pyx in gudhi.cubical_complex.CubicalComplex.cofaces_of_persistence_pairs()

ValueError: max() arg is an empty sequence

And I think the error is coming from src/python/gudhi/cubical_complex.pyx, line 219
https://github.com/GUDHI/gudhi-devel/blob/8dfc31c57586b07524728c939593f216c5d640f5/src/python/gudhi/cubical_complex.pyx?fbclid=IwAR3av9KK8BkAoji01SoMeXMtKJbeIFmlEav9m_P52Nerbrq6FX82XolGM8g#L219
the code is:
max_h = max(reg[:,0])+1
So when reg[:,0] is empty, (and this happens when the persistence diagram has no paired birth and death, i.e. having only one feature that doesn't die)
then it is calling max([]) and it returns that 'ValueError: max() arg is an empty sequence'.

And I think it can be fixed as changing that line to
if (len(reg[:,0]) == 0):
  max_h = 0
else:
  max_h = max(reg[:,0])+1

**Comment by MathieuCarriere** [comment]
Thanks a lot Jisu for spotting this error! I wrote a small PR that should solve it (using your recommendation).
