### ISSUE TITLE
Hera headers are attempted installed also when using external version

### ISSUE THREAD

**Issue by gspr** [GUDHI/gudhi-devel#346]
Thanks for facilitating the use of an external version of Hera through `HERA_WASSERSTEIN_INCLUDE_DIR`! 

However, even if that CMake flag is set, GUDHI attempts to install its bundled copy of Hera (`copy_directory ${CMAKE_SOURCE_DIR}/ext/hera/wasserstein/include …` in `src/cmake/modules/GUDHI_user_version_target.cmake`). This fails, and is generally undesirable, when using an external version. Could you please skip the installation of the Hera headers if for example that flag was manually set?

**Comment by mglisse** [comment]
We can do that, but let me try to understand first.
`make user_version` creates a copy of the sources ready for a release, from a git checkout. Are you using a git checkout instead of release tarballs? How is this copying failing for you?
A partial copy of hera is included in the release tarballs, but is ignored in the build process if you specify HERA_WASSERSTEIN_INCLUDE_DIR. Are you trying to avoid havind hera in the source tarball?
Actual installation should only install some binaries for hera, none of the sources.

**Comment by gspr** [comment]
Marc Glisse <notifications@github.com> writes:

> We can do that, but let me try to understand first.
> `make user_version` creates a copy of the sources ready for a release,
> from a git checkout. Are you using a git checkout instead of release
> tarballs? How is this copying failing for you?

Very good point, Marc! I actually have no idea why that make target is
being called in the first place – I was blindly looking for where it
failed, not what its actual purpose is.

I'll get back to you. Sorry for the noise!

**Comment by mglisse** [comment]
Ah, could it come from `make doxygen`? It is possible we have a problem there, I didn't check.

**Comment by gspr** [comment]
Gard Spreemann <gspr@nonempty.org> writes:

> Very good point, Marc! I actually have no idea why that make target is
> being called in the first place – I was blindly looking for where it
> failed, not what its actual purpose is.

Is it possible that the `doxygen` target depends on the `user_version`
target?

**Comment by gspr** [comment]
Marc Glisse <notifications@github.com> writes:

> Ah, could it come from `make doxygen`? It is possible we have a problem there, I didn't check.

Yes, exactly, that seems like it (sorry for double-commenting, there's a
bit of a delay in GitHub's e-mail interface).

**Comment by mglisse** [comment]
I thought it only depended on user_version if you tried to make it directly from a git checkout, not from a release tarball. And I don't see it build user_version here, I need to check.

**Comment by gspr** [comment]
Marc Glisse <notifications@github.com> writes:

> I thought it only depended on user_version if you tried to make it
> directly from a git checkout, not from a release tarball.

The Debian package is maintained as a branch off git master, and merges
in release tags. It makes my life a lot easier than dealing with the
tarballs. I'm happy to patch out the relevant part of user_version if
it's not convenient to change the behavior though.

**Comment by mglisse** [comment]
Locally, to build gudhi, I tend to first make user_version, and then build that. For instance, the python sphinx doc only works properly that way IIRC.
To avoid copying hera if the variable is set, I wonder if there is anything cleaner than setting a second (internal) variable with the same internal path, and checking if the 2 have the same value. Or maybe use `string(FIND, ...)` to check if HERA_WASSERSTEIN_INCLUDE_DIR starts with CMAKE_SOURCE_DIR?

**Comment by mglisse** [comment]
I tried something in e84f5d1b3c753147ac1601537b2be15ec118144e (on the branch that introduces a wrapper to hera's bottleneck distance). For the existing release, I think it is easier if you just remove the line that copies hera in the debian package.

**Comment by gspr** [comment]
Marc Glisse <notifications@github.com> writes:

> Locally, to build gudhi, I tend to first make user_version, and then
> build that. For instance, the python sphinx doc only works properly
> that way IIRC.

Ahh, I had no idea. Thanks! I'll start doing it like that too for the
next version, then. I'll enable the Python sphinx docs at some point
too; they were postponed for a while due to missing dependencies and I
never got around to it, but I believe that's all taken care of now.

> To avoid copying hera if the variable is set, I wonder if there is
> anything cleaner than setting a second (internal) variable with the
> same internal path, and checking if the 2 have the same value. Or
> maybe use `string(FIND, ...)` to check if HERA_WASSERSTEIN_INCLUDE_DIR
> starts with CMAKE_SOURCE_DIR?

I personally find string matching like that brittle, but I have no
strong feelings. Alternatively, one could have a CMake option à la
`EXTERNAL_HERA_INCLUDE_DIR` where, if unset, things happen as currently,
and if set, overrides `HERA_WASSERSTEIN_INCLUDE_DIR` and disables the
copying of Hera.

Whatever is easier to maintain for you guys.

**Comment by mglisse** [comment]
> Alternatively, one could have a CMake option à la `EXTERNAL_HERA_INCLUDE_DIR` where, if unset, things happen as currently, and if set, overrides `HERA_WASSERSTEIN_INCLUDE_DIR` and disables the copying of Hera.

That's a nice idea. I may try that if what I did fails for some reason.

**Comment by gspr** [comment]
Marc Glisse <notifications@github.com> writes:

> I'll try to refrain from introducing a dependency on pytorch for the doc... (for now)

This is not very important for me or the Debian package, just so you
know – I think people will be fine without local documentation. For the
Debian package, it is much much more important that a hard and required
dependency on PyTorch is not introduced. The situation of PyTorch in
Debian/Ubuntu is…  difficult at best. Of course I understand that GUDHI
development has to be primarily concerned with overall usefulness, but
also demanding that users install the sprawling and fast-moving behemoth
that is PyTorch would probably complicate things a lot. That's my 2
centimes anyway :-)

**Comment by gspr** [comment]
Vincent Rouvreau ***@***.***> writes:

>  Gard Spreemann ***@***.*** writes:
>  Very good point, Marc! I actually have no idea why that make target is being called in the first place – I
>  was blindly looking for where it failed, not what its actual purpose is.
>  Is it possible that the doxygen target depends on the user_version target?
>
> @gspr and @mglisse doxygen target now depends on the user_version. It has been done on #484 and
> released with gudhi 3.5.0. Does it mean this issue is closed or did I miss anything ?

I must admit I don't remember exactly what the issue was here, but
everything is in good shape wrt the user_version stuff as far as Debian
is concerned. So I think this issue can be closed.
