### ISSUE TITLE
WassersteinDistance default: POT or Hera

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#350]
https://github.com/GUDHI/gudhi-devel/blob/58f7cd2d1fec9b12665ad10c16b9812eba303570/src/python/gudhi/representations/metrics.py#L357

WassersteinDistance uses `mode="pot"` by default (and thus requires that POT be installed: https://github.com/GUDHI/TDA-tutorial/issues/17), while pairwise_persistence_diagram_distances with `metric="wasserstein"` uses Hera by default, that's not consistent.

**Comment by tlacombe** [comment]
As `mode=hera` has less dependencies, I guess it should be the default mode.

**Comment by mglisse** [comment]
ok, could you handle it in #349 please, at the same time as making the default parameters consistent? Ask Mathieu if you need help with something.

**Comment by tlacombe** [comment]
Done
