### ISSUE TITLE
Eigen is mandatory for Python compilation

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#388]
With #369 Edge Collapse is included by Python Simplex Tree.
This means no Python Simplex Tree when no Eigen, which means also no Alpha, no Rips, no Witness, no Cover, and no Tangential.

**Comment by mglisse** [comment]
Some choices:

1. Document everything that currently requires Eigen, and teach that to CMake
2. Make Eigen mandatory
3. Add some #ifdef so that only the edge collapse function depends on Eigen (and possibly move test_collapse_edges to its own file so it is easier to disable?)
