### ISSUE TITLE
bottleneck_distance([],[[.99,1.]]) returns .5 ???

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#399]
Actually, `gudhi.bottleneck_distance([],[[x,1.]])` returns .5 whatever the value of x smaller than 1 (I tried -10, 0, .9)...
Forcing epsilon=0 avoids the issue.
`gudhi.hera.bottleneck_distance` is fine.

**Comment by mglisse** [comment]
While looking at it, is seems that diameter_bound assumes that all the coordinates are non-negative?

**Comment by elasalle** [comment]
In fact, `gudhi.bottleneck_distance([],[[x,y]])` returns `.5 * y` when y>x.

**Comment by mglisse** [comment]
`alpha = std::pow(g.size(), 1. / 5.)` doesn't give such a great ratio when the size (sum of the diagrams) is 1. Maybe we just need a special case for that...
