### ISSUE TITLE
Sparse RipsComplex RuntimeError

### ISSUE THREAD

**Issue by xchhuang** [GUDHI/gudhi-devel#404]
Hi,

I got an "Unknown exception" error with sparse RipsComplex when I try to normalize the point positions as the following:
```
import tadasets
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import pairwise_distances
import time
import gudhi as gd

X = tadasets.infty_sign(n=100, noise=0.0)
X = (X + 1) / 2 # error with this line
tic = time.time()
D = pairwise_distances(X, metric='euclidean')
rips = gd.RipsComplex(distance_matrix=D, max_edge_length=42, sparse=0.1)
simplex_tree = rips.create_simplex_tree(max_dimension=2)
diag = simplex_tree.persistence(homology_coeff_field=2, min_persistence=0)
toc = time.time()
print ('Elapsed Time: {:.4f}'.format(toc-tic))
```

Error messages:
`File "rips_complex.pyx", line 102, in gudhi.rips_complex.RipsComplex.create_simplex_tree
RuntimeError: Unknown exception`

Is there any restriction for using the sparse rips complex ? Thanks for your help.

**Comment by mglisse** [comment]
The unknown exception is
> throw "Self-loops are not simplicial";

We should probably throw a standard exception so it gets converted to python more nicely. Now to investigate why we get there...

**Comment by xchhuang** [comment]
Hi @mglisse,

Thanks for your reply. I find that `sorted_points` in `Sparse_rips_complex.h` is updated by `choose_n_farthest_points`, is there a problem with the `choose_n_farthest_points`  function ?

**Comment by mglisse** [comment]
> is there a problem with the `choose_n_farthest_points` function ?

Yes, that's what my comment means. When it is passed a duplicate point, it gets confused about the last point (that won't be very hard to fix). You don't have duplicate points, so I need to check carefully if you are still hitting essentially the same issue or some completely different issue with the same code (or with the code preparing data for this function).

**Comment by xchhuang** [comment]
Hi,

Indeed there are points too close in my test cases, thanks for pointing this out!

**Comment by xchhuang** [comment]
Hi @mglisse,

Just a followup, if this pull request is merged to the master branch, do I need to compile from source to get it? Or it would work by pip/conda install? And how long does the pull request usually take ? Thanks in advance.

**Comment by mglisse** [comment]
The default pip/conda will only work after the next release (unless we start uploading experimental packages built from trunk regularly, but we don't do that currently), which could be a couple months away. Building from source is always an option. We were trying to have continuous integration build experimental pip packages (that you would have to download manually before running pip on that file), and you may be able to see lines like "pip build linux / build pip wheels (pull_request) Successful in 5m" at the bottom of the pull request, but maybe it is only a test currently and doesn't make the result available, @VincentRouvreau would know but he is not available right now.

**Comment by xchhuang** [comment]
Thanks. Yes I can see the pull request, that would be great to have the wheels file to install. 

I tried building from source but there seems to have some other unexpected errors compared with the official pip release...

**Comment by mglisse** [comment]
Thanks a lot for your bug report, the testcase was very helpful.
If you are getting other errors when building from source, feel free to open a separate issue about that.
