### ISSUE TITLE
make install puts Miniball.README in include

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#414]
In `make install`, we copy Miniball.README and Miniball.COPYRIGHT to the include directory, which we probably shouldn't do.

**Comment by VincentRouvreau** [comment]
I placed Miniball.README and Miniball.COPYRIGHT in `src/Cech_complex/include/gudhi` and all the `include/gudhi` are copied and installed. I think it is important to install the COPYRIGHT file (the README is not that important...) or do you think https://gudhi.inria.fr/licensing/ is clear enough ?

**Comment by mglisse** [comment]
We don't install any license for the rest of gudhi. If we want to install it, include/ might not be the best place (?). The beginning of the file does mention its license. We should indeed clarify that miniball is shipped with gudhi: that makes it different from the other dependencies where if you don't install a GPL dependency, you are "safe".

**Comment by mglisse** [comment]
km.py.COPYRIGHT also gets installed, and this one seems less useful since the license is MIT.

**Comment by gspr** [comment]
FWIW, we manually delete these files from `include/gudhi` in the Debian package.

**Comment by mglisse** [comment]
miniball was removed in #519.
