### ISSUE TITLE
AlphaComplex confusing message for 3D points on a plane

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#448]
```python
>>> import gudhi
>>> gudhi.AlphaComplex(points=[[1.,0.,0.]]).create_simplex_tree()
Alpha_complex_3d create_complex - no triangulation as points are on a 2d plane
<gudhi.simplex_tree.SimplexTree object at 0x7f244ed61ed0>
```
But it does produce a simplicial complex with one vertex. The message that is printed is causing some confusion for users. Since there is a fallback, calling the python code should not print this message. (or at least we could make it clearer that python users can ignore this message)

**Comment by VincentRouvreau** [comment]
The message print comes from https://github.com/GUDHI/gudhi-devel/blob/7e05e915adc1be285e04eb00d3ab7ba1b797f38d/src/Alpha_complex/include/gudhi/Alpha_complex_3d.h#L464-L466
I think throwing an exception would be more appropriate in this case. Do you agree ?

**Comment by mglisse** [comment]
There are 2 places that return false in this function, we may want to avoid having 3 different error reporting mechanisms for the same function.
Printing a message means we consider this an error, i.e. the user should have checked something before calling the function.
If we consider it normal to call the function even in the bad case, then we have to report the issue, for instance by returning false without printing anything, or with an exception. I don't have a strong opinion right now about which one is better, the exception seems ok if that's your preference. Then we can probably turn the check for a non-empty complex into an assertion, and we don't need to return anything anymore?

**Comment by VincentRouvreau** [comment]
I think that would fit better my needs for the python side. Let's go with exceptions.

**Comment by mglisse** [comment]
While this doesn't affect our python interface anymore, would it make sense to add a function `is_full_dimensional` that a user could call before create_complex to check if it is going to work?
