### ISSUE TITLE
[Python - persistence_graphical_tools] warn when plot drops some intervals

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#453]
The plotting functions have a parameter `max_intervals=1000` which means that some intervals are not shown. This can be confusing for users, and printing a warning when that happens could help. Of course, that same warning could annoy users who specifically asked for this behavior, maybe it could be restricted to the default case or have a way to disable it.

**Comment by pdlotko** [comment]
Suggest to print the warning by default, and skip it only a shut_up flag is set explicitly by the user.
