### ISSUE TITLE
Potential Bug in Sparse Rips Complex

### ISSUE THREAD

**Issue by JackRDoyle** [GUDHI/gudhi-devel#456]
The calculation of the sparse rips complex (using Python) gives an error for my specific point cloud - which is quite symmetrical. I attach the corresponding (60x60) distance matrix as a txt file. GitHub won't let me pick at better file format -sorry. 

I have not yet found any other examples which give the same error and the unweighted rips complex works well. Furthermore if I perturb all points by a set of very small random numbers the calculation works as desired. The unpredictable nature of the error makes it hard for me to deal with systematically, however. 

When using my mac OS (10.14.6) I get a python runtime error - 'Unknown Error'.

When using my Ubuntu machine (16.04.6) I get a different error that has apparently leaked out of the python wrapper:
"_terminate called after throwing an instance of 'char const*'_"

Thanks

[distance_matrix_that_causes_error.txt](https://github.com/GUDHI/gudhi-devel/files/6075290/distance_matrix_that_causes_error.txt)

**Comment by mglisse** [comment]
Thank you for the report. Could you tell us which version of gudhi you are using, and provide a small python program (probably less than 10 lines) that shows this error, so we can be sure we are looking at the same thing?

**Comment by JackRDoyle** [comment]
I am using gudhi 3.3.0.  Here is a minimal example of code that produces the error. I load the relevant distance matrix from an npy file which I sadly can't attach to the GitHub thread. 

`import numpy as np
import gudhi as gd


#load in distance matrix
dm = np.load('./test_dm.npy', allow_pickle=True)

#error with sparse rips complex only
rips = gd.RipsComplex(distance_matrix = dm, max_edge_length = 5, sparse = 0.5)

#error occurs next line
simplex_tree = rips.create_simplex_tree(max_dimension = 3)

diag = simplex_tree.persistence()`

**Comment by mglisse** [comment]
We fixed the related bug #404 in gudhi 3.4, could you try upgrading to see if it fixes the issue for you?

**Comment by JackRDoyle** [comment]
I have updated Gudhi and I now get a different set of errors pertaining to memory corruption. The error messages I get depend: on the machine I use; whether I run the code from the command line or from jupyter and the sparseifcation parameter. 

This is the error I get from the command line on my mac:

python3(19024,0x115fa45c0) malloc: Incorrect checksum for freed object 0x7f9c2b45b8e8: probably modified after being freed.
Corrupt value: 0x40010c18fdc03020
python3(19024,0x115fa45c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

I was able to get a diagram out for my minimal case only on jupyter (but not from my script with the same data and parameters) with s=0.1 and a max_edge_length = 5. The diagram it gave had lots of 1D features which did not die which were not present in the diagram for the unmodified Rips filtration. 

Like this:

![image](https://user-images.githubusercontent.com/50619260/109804910-b7d33c00-7c1a-11eb-950e-18200c8827e0.png)

**Comment by mglisse** [comment]
I am getting a good diagram with sparse=.5 (without plenty of infinite points, unlike your picture), and sometimes with .1, but other times I am getting a crash, I'll have to investigate that.

**Comment by mglisse** [comment]
Ok, the fix for #404 was incomplete, there is a vector I am under-allocating when there are redundant input points.
Until this is fixed, a simple workaround is to remove duplicated points: here for instance you have points 0 and 4 at distance 0, so you can remove one of them, etc.
