### ISSUE TITLE
ModuleNotFoundError: No module named 'gudhi.weighted_rips_complex'

### ISSUE THREAD

**Issue by n-otter** [GUDHI/gudhi-devel#464]
With version 3.4.1 installed using Conda, when running

```
import gudhi
from gudhi.weighted_rips_complex import WeightedRipsComplex
```

I get the error message 

`ModuleNotFoundError: No module named 'gudhi.weighted_rips_complex'`

**Comment by mglisse** [comment]
Hello,
what version is it, windows? linux? 64 bits? etc.

**Comment by n-otter** [comment]
It's linux 64 bits, with OS openSUSE Leap 42.3

**Comment by mglisse** [comment]
python 3.9?

**Comment by n-otter** [comment]
No, python 3.7.

**Comment by mglisse** [comment]
I just tried with conda-forge/linux-64::gudhi-3.4.1-py37h7f1c583_1 and the import works fine for me...

**Comment by mglisse** [comment]
Could you try, after `import gudhi`, to print `print(gudhi.__version__)` and `print(gudhi.__path__)`? Maybe you have an older pip version that is interfering.

**Comment by n-otter** [comment]
Yes, I think that your guess is correct, since I get 
```
>>> print(gudhi.__version__)
3.1.1
```
and
```
>>> print(gudhi.__path__)
['/opt/anaconda3/lib/python3.7/site-packages/gudhi']
```

**Comment by VincentRouvreau** [comment]
@n-otter I am closing the is issue as the GUDHI version was not the correct one.
