### ISSUE TITLE
Reeb graphs in Python?

### ISSUE THREAD

**Issue by annasongmaths** [GUDHI/gudhi-devel#466]
Hi all,

Thanks a lot for your great library!

Are you considering adding support for Reeb graph computation in Python? I haven't been able to find any Python implementation on the internet, although some codes are available in C++ (as in ttk), Java or Haskell. Maybe, since a lot of algorithms have been proposed around 2010, these codes have already been integrated somewhere?
I wonder if I am missing something, or if you have some plan to work on Reeb graphs in the future: they would fit well with Gudhi, and would certainly benefit their usage in e.g. biological applications.

Thank you for your time!
Best regards,
Anna

**Comment by mglisse** [comment]
Hello,
could you be more specific about the type of data for which you want to compute a Reeb graph? Does it come as a point cloud? As a simplicial complex, with function values at the vertices, and the function is implicitly the linear interpolation? Something else?

The closest we have currently is https://gudhi.inria.fr/python/latest/nerve_gic_complex_user.html (and soon #403).

**Comment by annasongmaths** [comment]
Hi,

Thank you very much for your quick reply and the links! I am interested in computing a Reeb graph for the height function on a surface (triangular mesh), but I would also be interested in computing it for a simplicial complex built upon a point cloud sampled from the surface.
I will definitely look into the references you mention, thanks a lot. From what I understand, it seems that alternatives to Reeb graphs, such as Mapper, are preferred over the original Reeb graphs, which may explain why there has not been so much Python implementations.

Best regards,
Anna

**Comment by mglisse** [comment]
Mapper isn't "preferred" over Reeb. What happens is that in many cases, you do not have a mesh but only a point cloud. In that case, you cannot compute a Reeb graph, and mapper is a nice approximation. If you do have a simplicial complex (or even a mesh), then using and computing the true Reeb graph makes sense, and there are indeed efficient algorithms for that (10.1145/1810959.1811005 for instance). However, we haven't implemented or wrapped any in gudhi for now.

**Comment by annasongmaths** [comment]
OK I see, thank you for the clarification!
I will close this issue.

Best,
Anna
