### ISSUE TITLE
Face normal vector is inconsistent

### ISSUE THREAD

**Issue by CharyPro** [GUDHI/gudhi-devel#467]
I want to try this example of **RipsContraction**，When I call `Skeleton_blocker_off_reader` this function to Read an off file，then call the `Skeleton_blocker_off_writer` function to save it. But the normal of saving results is inconsistent，I haven't done anything, just read and save it，as shown below：
![inconsistent](https://user-images.githubusercontent.com/28482661/113677761-80abeb00-96f0-11eb-9220-a0aa487db690.png)

The picture below is normal：
![normal](https://user-images.githubusercontent.com/28482661/113677836-94efe800-96f0-11eb-8397-f5cd5806b2dd.png)

How to solve this situation？thanks.

**Comment by VincentRouvreau** [comment]
Hello, and thank you for the report @CharyPro 
How did you call `Skeleton_blocker_off_reader` ?
In `RipsContraction` it is called like this:
```cpp
Gudhi::skeleton_blocker::Skeleton_blocker_off_reader<Complex> off_reader(argv[1], complex, true);
```
The last argument (true) means to load only the points.
I replayed this unitary test https://github.com/GUDHI/gudhi-devel/blob/7e05e915adc1be285e04eb00d3ab7ba1b797f38d/src/Skeleton_blocker/test/test_skeleton_blocker_geometric_complex.cpp#L35-L49 and it seems to work for me.
Be aware, like explained in the source code https://github.com/GUDHI/gudhi-devel/blob/7e05e915adc1be285e04eb00d3ab7ba1b797f38d/src/Skeleton_blocker/include/gudhi/Skeleton_blocker/Skeleton_blocker_off_io.h#L143-L149 that only triangles are written in the output file.
I hope this will help to understand the issue you are facing.

**Comment by CharyPro** [comment]
Thanks for your replay @VincentRouvreau    

I know what you mean，but my code is written like this：
```
 Complex complex;

  Gudhi::skeleton_blocker::Skeleton_blocker_off_reader<Complex> off_reader("cube.off", complex);
  if (!off_reader.is_valid()) {
    std::cerr << "Unable to read file:" << "cube.off" << std::endl;
    return EXIT_FAILURE;
  }

  Gudhi::skeleton_blocker::Skeleton_blocker_off_writer<Complex> off_writer("result.off", complex);
```
I noticed that the off file you used for testing is a flat model, I use the following simple cube model to test.
```
OFF
8 12 0
-0.274878 -0.274878 -0.274878
-0.274878  0.274878 -0.274878
 0.274878  0.274878 -0.274878
 0.274878 -0.274878 -0.274878
-0.274878 -0.274878  0.274878
-0.274878  0.274878  0.274878
 0.274878  0.274878  0.274878
 0.274878 -0.274878  0.274878
3  0 1 3
3  3 1 2
3  0 4 1
3  1 4 5
3  3 2 7
3  7 2 6
3  4 0 3
3  7 4 3
3  6 4 7
3  6 5 4
3  1 5 6
3  2 1 6
```
The final saved result is as follows:

![normal](https://user-images.githubusercontent.com/28482661/113821167-53be0d80-97ae-11eb-95ad-3f8f5ff3cc31.png)
![error](https://user-images.githubusercontent.com/28482661/113821169-5587d100-97ae-11eb-9075-ba62d0e5406f.png)
The first picture is the original model, and the second picture is the model after reading and saving. Blue indicates that the normal vector is facing outward, and red indicates that the normal vector is facing inward

You can test it with my model above

**Comment by mglisse** [comment]
Sorry, this package does not care about the orientation of triangles. It can work with complexes that are not manifold, not orientable, etc. In the internal storage, whatever order you had on the vertices in your original OFF file is lost. If you want to recover consistent orientations, you will need to use some separate tool (not from gudhi) as postprocessing.

**Comment by CharyPro** [comment]
Thanks for your reply. I have solved this problem with other methods.
