### ISSUE TITLE
Python gudhi package shall not be installed with 'make install'

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#468]
gudhi C++ library requires the user to have the proper privileges to be able to install header files. On UNIX systems, as files are installed in `/usr/local` ([source](https://cmake.org/cmake/help/v3.0/variable/CMAKE_INSTALL_PREFIX.html)), this results to install the library by doing:
```bash
sudo make install
```
The user can tweak the installation directory by calling:
```bash
make DESTDIR=/my/directory install
```

The issue with the gudhi python package is that `sudo make install` will lead to do `sudo python setup.py install`.
This is not working if some dependencies are not in the sudoers PATH (cython, for instance).
Moreover, it does not exist already, it will create a directory `/usr/local/lib/python3.X/dist-packages/` with the super user ownership, which is not a good idea as all other future installations will require administrator privileges thereafter (cf. `sudo pip install` vs `pip install --user` posts).
Finally, it is not possible to retrieve `DESTDIR` (or I didn't find how) and I had to document how to install in a different directory by doying `python setup.py install --prefix /my/directory`.

After a quick analysis, I think we should remove python installation through the `make install` command cf. https://github.com/GUDHI/gudhi-devel/blob/7e05e915adc1be285e04eb00d3ab7ba1b797f38d/src/python/CMakeLists.txt#L277
And we should only document to install the python library by doing `python setup.py install`.

**Comment by mglisse** [comment]
> The user can tweak the installation directory by calling:
> 
> ```shell
> make DESTDIR=/my/directory install
> ```

Using DESTDIR is rather specific, the more natural way to choose an install location is with `cmake -DCMAKE_INSTALL_PREFIX=/path/to/somewhere`.

>  And we should only document to install the python library by doing `python setup.py install`.

If noone comes up with a better strategy, ok.
Does `pip install .` also work?

> Finally, it is not possible to retrieve `DESTDIR`

?
