### ISSUE TITLE
scipy renamed n_jobs to workers

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#473]
> gudhi/point_cloud/knn.py:308: DeprecationWarning: The n_jobs argument has been renamed "workers". The old name "n_jobs" will stop working in SciPy 1.8.0.

My favorite option is to blame scipy (they renamed it to be consistent with 2 other functions in scipy, but nobody else uses this name). However, it does not solve the problem.

1. I could translate n_jobs to workers (I already translate it to num_threads for another library), but then it would fail with previous versions of scipy, and I am not sure about requiring 1.6+. We could also wait a bit, pretending the warning is not there, until we are forced to change, and maybe that's far enough in the future that requiring scipy version 1.6+ will be fine.
2. I could use `packaging.version.parse(scipy.__version__)` to see if the version is at least 1.6 and do the renaming conditionally, but that's more code and an extra dependency.

**Comment by VincentRouvreau** [comment]
Scipy 1.6+ is quite recent (december 2020), but ok if we go for it. We will have to document it in the [Scipy installation procedure](https://gudhi.inria.fr/python/latest/installation.html#scipy) and modify the [test requirements](https://github.com/GUDHI/gudhi-deploy/blob/main/test-requirements.txt)

**Comment by mglisse** [comment]
Fixed by #717 (dup #662).
