### ISSUE TITLE
[cython] Simplex_tree_interface_full_featured's constructor

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#485]
https://github.com/GUDHI/gudhi-devel/blob/70387c34b638972b7c51017b81949f32ddd63e39/src/python/gudhi/simplex_tree.pxd#L46-L47

It is strange that the constructor is not using the same name as the class, is that a typo?

**Comment by Hind-M** [comment]
I don't know if using two different names was intended, but replacing _Simplex_tree_ with _Simplex_tree_interface_full_featured_ does resolve the problem with the copy constructor #131. I find it weird that it was compiling and working without any errors all along...

**Comment by mglisse** [comment]
I find this strange as well. If you want to spend a bit of time preparing a bug report for cython, asking them to print a diagnostic for this kind of issue, don't hesitate. If you don't feel like it, that's fine as well.

**Comment by Hind-M** [comment]
I created an issue for cython: https://github.com/cython/cython/issues/4141
