### ISSUE TITLE
RipsComplex out of bounds access

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#489]
With this patch (don't commit it, it is just to show the issue without a non-portable debug mode)
```patch
--- a/src/Rips_complex/include/gudhi/Rips_complex.h
+++ b/src/Rips_complex/include/gudhi/Rips_complex.h
@@ -84,7 +84,7 @@ class Rips_complex {
   template<typename DistanceMatrix>
   Rips_complex(const DistanceMatrix& distance_matrix, Filtration_value threshold) {
     compute_proximity_graph(boost::irange((size_t)0, distance_matrix.size()), threshold,
-                            [&](size_t i, size_t j){return distance_matrix[j][i];});
+                            [&](size_t i, size_t j){return distance_matrix.at(j).at(i);});
   }
 
   /** \brief Initializes the simplicial complex from the Rips graph and expands it until a given maximal
```
> 11/40 Test #22: rips_complex_diagram_persistence_from_distance_matrix_file_example_py_test ...........***Failed    0.17 sec
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 2) >= this->size() (which is 2)
Child aborted

**Comment by Hind-M** [comment]
Wouldn't it be useful and more meticulous to use the `at` ?

**Comment by mglisse** [comment]
That would violate the concept, this function is supposed to work for some ranges that have `operator[]` but not `at`.
It is also not free, this is a general question of how defensive we want to be. In general, unless the check is really completely negligible even for small sizes, I tend to favor speed for the C++ code. Most compilers have some debug mode that can be turned on to make `vector::operator[]` check the bounds during development, and then we can go back to being fast for production. Or if the caller wants to, they can validate the input themselves before passing it on.
On the other hand, here, in the python interface, having a loop that checks that `m[i].size()>=i` (or whatever the condition is) before feeding `m` to the "unsafe" Rips_complex would be perfectly fine with me.

**Comment by VincentRouvreau** [comment]
Maybe complicated, but a good idea would be to pass the test suite with a sanitizer on CI.

As exceptions are not cost less, I would continue with `operator[]`.
