### ISSUE TITLE
[Tests] test_rips_complex_py_test fails

### ISSUE THREAD

**Issue by Hind-M** [GUDHI/gudhi-devel#491]
Generates the following errors :

.test_sparse_with_multiplicity
malloc_consolidate(): invalid chunk size
Aborted (core dumped)

>       assert simplex_tree.num_simplices() == 7
E       assert 16 == 7
E        +  where 16 = <built-in method num_simplices of gudhi.simplex_tree.SimplexTree object at 0x7f11bf7d8d80>()
E        +    where <built-in method num_simplices of gudhi.simplex_tree.SimplexTree object at 0x7f11bf7d8d80> = <gudhi.simplex_tree.SimplexTree object at 0x7f11bf7d8d80>.num_simplices

../src/python/test/test_rips_complex.py:155: AssertionError

**Comment by Hind-M** [comment]
By the way, do we have a workflow for running tests with pull requests ? Or running them in the master branch every X hours/days/weeks ?

**Comment by mglisse** [comment]
Is that current master? On what platform is that? (compiler, versions, etc) It works here, and I have tested it with the address sanitizer... I am surprised it reaches an assertion failure if it already aborted before that.

Yes we run the tests in PRs, you can see the results at the bottom of every PR, and on https://github.com/GUDHI/gudhi-devel you can see badges (passed/fail) for master. I think the tests for master are run at every merge, Vincent knows.

**Comment by VincentRouvreau** [comment]
Yes that's it, tests are run at every merge on master and at every push on your PR. We do not run at X hours/days/weeks.

**Comment by Hind-M** [comment]
> Is that current master? On what platform is that? (compiler, versions, etc) It works here, and I have tested it with the address sanitizer... 

Yes, current master, Ubuntu 20.04, cmake 3.16.3, python 3.8.5

> I am surprised it reaches an assertion failure if it already aborted before that.

Actually, that was two different errors generated with two different test runs.

**Comment by mglisse** [comment]
I tried reproducing it in a docker with ubuntu 20.04 using either no option for CMake or just `-DCMAKE_BUILD_TYPE=Release` and running the test a hundred times never fails.
Any hint on what I can do to reproduce the issue?

**Comment by Hind-M** [comment]
I tried it again on a new branch based on current master and within a clean build, it works fine. It must have been some leftovers in my build ... Sorry for the false alarm ...

**Comment by mglisse** [comment]
Ok, do re-open if it hits again. There are other issues that some people hit and we have trouble reproducing...

**Comment by mglisse** [comment]
My guess would be that you got a recent version of master, with the new test, then switched to an older version/branch, but somehow kept the test, and thus you hit the problem that was fixed at the same time the test was introduced.

**Comment by Hind-M** [comment]
Yes, very likely !
