### ISSUE TITLE
Sources missing submodules

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#505]
https://gudhi.inria.fr/ -> download -> get the latest sources
sends me to https://github.com/GUDHI/gudhi-devel/releases/tag/tags/gudhi-release-3.4.1.post2
which only contains the github-generated archives (tar.gz and zip), which do not contain the submodules (because of https://github.community/t/create-release-that-contains-submodule/1329). That's very inconvenient. I think we used to provide real, complete source tarballs. And the documentation does not mention that we need to download other sources to complete those.

**Comment by mglisse** [comment]
Ah, I see that the real 3.4.1 release does have a suitable gudhi.3.4.1.tar.gz, it is only because of the fake post release that things are getting messed up.

**Comment by VincentRouvreau** [comment]
I built the gudhi-release-3.4.1.post2.tar.gz and is now available in [the release note](https://github.com/GUDHI/gudhi-devel/releases/tag/tags/gudhi-release-3.4.1.post2)
