### ISSUE TITLE
[Question] Iterate on L_j of simplex tree

### ISSUE THREAD

**Issue by SILIZ4** [GUDHI/gudhi-devel#510]
In the article [_The Simplex Tree: An Efficient Data Structure for General Simplicial Complexes_](https://link.springer.com/article/10.1007/s00453-014-9887-3) from Jean-Daniel Boissonnat & Clément Maria, they use a circular list L_j(k) to link the simplices of the same dimension j that contain the same label k. I figured that Gudhi probably uses the data structure described in that article so it probably supports that feature. I went through the Doxygen [documentation](gudhi.gforge.inria.fr/doc/latest/class_gudhi_1_1_simplex__tree.html) but I couldn't find an iterator/range for that functionality. Is there any way to do so?

**Comment by mglisse** [comment]
Sorry, this part is not implemented in gudhi currently. #401 contains code for this (although I think it links simplices of all dimensions) but we haven't found time to integrate it yet.
