### ISSUE TITLE
Compatibility with Apple M1/ARM64 Silicon

### ISSUE THREAD

**Issue by astamm** [GUDHI/gudhi-devel#533]
Currently, GUDHI-Python can be installed via `pip install` but is not listed as available on [conda-forge](https://anaconda.org/conda-forge/repo). On Apple M1 silicon architectures, there is therefore no option for running it natively. It would be helpful to either upload native ARM64 wheels for macOS or make GUDHI available on [conda-forge](https://anaconda.org/conda-forge/repo) from which the [miniforge3](https://github.com/conda-forge/miniforge#download) project, which builds macOS ARM64 binaries via cross-compilation, fetches Python packages.

**Comment by astamm** [comment]
Thanks for the pointer to conda-forge. Strangely, I could not find it. Nice to read that an arm64 build is on its way, thanks!

**Comment by nikmihale** [comment]
Hello, @VincentRouvreau . Sorry to bother you, but is there an estimate for the 3.5.0 version release date?

**Comment by VincentRouvreau** [comment]
@nikmihale It is in progress. I will build the conda package for Apple M1 right after the version and pip package is available.

**Comment by VincentRouvreau** [comment]
@astamm @nikmihale If one of you has the opportunity to test it, the [conda package for the release candidate 3.5.0rc2](https://anaconda.org/conda-forge/gudhi/files) is available on osx-arm64.
I will close the issue when the release (not candidate) will be done.

**Comment by astamm** [comment]
I have an iMac with M1 proc, I will be at the office next Thursday. I will try it then.

**Comment by VincentRouvreau** [comment]
The conda package is available for osx-arm64 and gudhi 3.5.0
