### ISSUE TITLE
Cannot install gudhi on python 3.10

### ISSUE THREAD

**Issue by DavidLapous** [GUDHI/gudhi-devel#550]
The command `pip install --user gudhi` fails with python 3.10.0 (on an up to date fedora 35) on my laptop :
```
ERROR: Could not find a version that satisfies the requirement gudhi (from versions: none)
ERROR: No matching distribution found for gudhi
```
I suppose that this issue comes from python 3.10 as other python libraries  such as `ot` aren't installing either.

**Comment by VincentRouvreau** [comment]
@DavidLapous Yes that's it. And we also have a compilation issue on windows that delays the release.
By the way, the conda package is already available for python 3.10.
