### ISSUE TITLE
Building with Debug and Benchmark option fails

### ISSUE THREAD

**Issue by Hind-M** [GUDHI/gudhi-devel#554]
Building with -`DCMAKE_BUILD_TYPE=Debug` and `-DWITH_GUDHI_BENCHMARK=ON` fails.
It seems that it is related to TBB linking regarding some benchmark files: `src/Toplex_map/benchmark/benchmark_tm.cpp` and `src/common/benchmark/Graph_simplicial_complex_benchmark.cpp`.
After adding the link in the corresponding CMakeLists.txt of the involved benchmark directories, some tests fail...

**Comment by mglisse** [comment]
Ah, #117 parlait déjà de problèmes avec debug et tbb, mais c'était juste pour python, pas pour les benchmarks...
