### ISSUE TITLE
make_filtration_non_decreasing in Alpha_complex_3d

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#57]
https://github.com/GUDHI/gudhi-devel/blob/a33d17ebb1a5f7c830ee155ec2733a0f48211010/src/Alpha_complex/include/gudhi/Alpha_complex_3d.h#L568

I wonder if this is always necessary. At least in the _exact_ case I don't think it is, I am not sure about the _safe_ and _fast_ cases. Anyway the current code is safe, and I doubt the cost matters, this is more of a remark.

**Comment by VincentRouvreau** [comment]
Hmm... I tried with `data/poits/tore3D_1307.off` with and without `make_filtration_non_decreasing` in safe, exact and fast mode, but the resulted simplex tree is always the same, it won't help to decide...

**Comment by VincentRouvreau** [comment]
# Benchmark with/without make_filtration_non_decreasing

## 4-D

data | algo | time in sec with make_filtration_non_decreasing | time in sec without make_filtration_non_decreasing | equal/different
--- | --- | --- | --- | ---
grid 15x15x15x15 | alpha dD exact | 299,202 | 298,069 | equal
grid 15x15x15x15 | alpha dD safe  | 248,714 | 244,171 | different
grid 15x15x15x15 | alpha dD fast  | 165,935 | 164,524 | different
2-image | alpha dD exact | 5,581 | 5,602 | equal
2-image | alpha dD safe  | 3,387 | 3,358 | different
2-image | alpha dD fast  | 2,712 | 2,763 | different
finance_4d_5000 | alpha dD exact | 33,605 | 33,388 | equal
finance_4d_5000 | alpha dD safe  | 9,020 | 8,683 | equal
finance_4d_5000 | alpha dD fast  | 8,647 | 8,185 | equal
finance_4d_8000 | alpha dD exact | 56,270 | 55,694 | equal
finance_4d_8000 | alpha dD safe  | 14,707 | 14,054 | equal
finance_4d_8000 | alpha dD fast  | 14,349 | 13,784 | equal

## 3-D

data | algo | time in sec with make_filtration_non_decreasing | time in sec without make_filtration_non_decreasing | equal/different
--- | --- | --- | --- | ---
grid 50x50x50 | alpha 3D exact | 72,657 | 72,865 | equal
grid 50x50x50 | alpha 3D safe  | 72,262 | 73,069 | equal
grid 50x50x50 | alpha 3D fast  | 38,286 | 37,480 | different
grid 50x50x50 | alpha dD exact | 84,923 | 84,180 | equal
grid 50x50x50 | alpha dD safe  | 64,234 | 63,127 | different
grid 50x50x50 | alpha dD fast  | 55,612 | 55,473 | different
grid 70x70x70 | alpha 3D exact | 213,911 | 209,666 | equal
grid 70x70x70 | alpha 3D safe  | 208,542 | 205,748 | equal
grid 70x70x70 | alpha 3D fast  | 113,571 | 113,131 | different
grid 70x70x70 | alpha dD exact | 259,230 | 255,493 | equal
grid 70x70x70 | alpha dD safe  | 201,138 | 198,142 | different
grid 70x70x70 | alpha dD fast  | 178,161 | 177,380 | different
grid 90x90x90 | alpha 3D exact | 450,077 | 447,440 | equal
grid 90x90x90 | alpha 3D safe  | 437,696 | 439,325 | equal
grid 90x90x90 | alpha 3D fast  | 243,841 | 237,737 | different
grid 90x90x90 | alpha dD exact | 724,270 | 727,723 | equal
grid 90x90x90 | alpha dD safe  | 592,397 | 585,862 | different
grid 90x90x90 | alpha dD fast  | 551,342 | 554,767 | different
finance_3d 5000 | alpha 3D exact | 3,029 | 3,087 | equal
finance_3d 5000 | alpha 3D safe  | 1,577 | 1,504 | equal
finance_3d 5000 | alpha 3D fast  | 1,440 | 1,428 | equal
finance_3d 5000 | alpha dD exact | 3,526 | 3,414 | equal
finance_3d 5000 | alpha dD safe  | 1,339 | 1,292 | equal
finance_3d 5000 | alpha dD fast  | 1,297 | 1,361 | equal
finance_3d 8000 | alpha 3D exact | 5,019 | 4,997 | equal
finance_3d 8000 | alpha 3D safe  | 2,596 | 2,660 | equal
finance_3d 8000 | alpha 3D fast  | 2,385 | 2,259 | equal
finance_3d 8000 | alpha dD exact | 5,638 | 5,589 | equal
finance_3d 8000 | alpha dD safe  | 2,172 | 2,181 | equal
finance_3d 8000 | alpha dD fast  | 2,104 | 2,040 | equal
run around acc | alpha 3D exact | 4,562 | 4,535 | equal
run around acc | alpha 3D safe  | 2,534 | 2,360 | equal
run around acc | alpha 3D fast  | 2,306 | 2,182 | different
run around acc | alpha dD exact | 5,083 | 5,000 | equal
run around acc | alpha dD safe  | 2,058 | 2,012 | different
run around acc | alpha dD fast  | 2,005 | 1,924 | different
run around mag | alpha 3D exact | 0,975 | 0,941 | equal
run around mag | alpha 3D safe  | 0,526 | 0,526 | equal
run around mag | alpha 3D fast  | 0,496 | 0,473 | equal
run around mag | alpha dD exact | 1,079 | 1,082 | equal
run around mag | alpha dD safe  | 0,469 | 0,459 | equal
run around mag | alpha dD fast  | 0,454 | 0,444 | equal

## Conclusion

We can safely remove make_filtration_non_decreasing in exact mode, but the gain won't be that much
