### ISSUE TITLE
Problem in installing the gudhi Python module

### ISSUE THREAD

**Issue by chengjunyi55** [GUDHI/gudhi-devel#573]
After installing via pip "pip install gudhi", I got "ModuleNotFoundError: No module named 'gudhi'" when trying to import the module.

I then tried installing the c++ package and compiling the python module from source:

cd /gudhi.3.5.0/
mkdir build
cd build/
cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=ON ..
make

The c++ package alone seems to work fine, but then when I did

cd python
make

nothing happened, and no setup.py file appeared either. Do you know what the problem might be? Thanks a lot!

**Comment by mglisse** [comment]
> After installing via pip "pip install gudhi", I got "ModuleNotFoundError: No module named 'gudhi'" when trying to import the module.

Could you tell us precisely which platform (type of processor, OS) you are using? And what python (from the OS, conda, self-installed, version)? Did pip say anything? Did something appear in `~/.local/lib/python*/site-packages/` (or wherever your other pip packages end up)? My first guess would be that you installed gudhi for one version of python but are then using a different version of python. How are you starting python? If you call it as `python3.9`, then it may be safer to use `python3.9 -m pip install gudhi`.

> I then tried installing the c++ package and compiling the python module from source:
> 
> cd /gudhi.3.5.0/ mkdir build cd build/ cmake -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=ON .. make
> 
> The c++ package alone seems to work fine, but then when I did
> 
> cd python make
> 
> nothing happened, and no setup.py file appeared either. Do you know what the problem might be?

Most likely you are missing a dependency, it is hard to tell without seeing what `cmake` printed.

**Comment by chengjunyi55** [comment]
I realized that the problem was due to an incorrect PYTHONPATH and fixed it. Thank you very much for your help!

**Comment by VincentRouvreau** [comment]
Installation is fixed, I close the issue
