### ISSUE TITLE
[Python] Enhance third parties version detection

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#580]
Python third parties version detection could be enhanced in [`find_python_module`](https://github.com/GUDHI/gudhi-devel/blob/7f1b8eb706c72921141b53e607d6e2aa28e2bf19/src/cmake/modules/GUDHI_third_party_libraries.cmake#L103) using:
```python
from importlib.metadata import version; print(version('hnswlib'))
# 0.6.0
```

* This would remove `find_python_module_no_version`
* Requires to do `find_python_module("scikit-learn")`
* Requires to do `find_python_module("POT")`

But [importlib metadata](https://docs.python.org/3/library/importlib.metadata.html) requires python 3.8, and for the moment gudhi requires 3.5.

**Comment by mglisse** [comment]
> But [importlib metadata](https://docs.python.org/3/library/importlib.metadata.html) requires python 3.8, and for the moment gudhi requires 3.5.

Python 3.7's EOL was last June, it seems ok to require 3.8+ in future releases.
(posting this here, but it may apply to other issues)
