### ISSUE TITLE
[bug] a strange result of extended_persistentce

### ISSUE THREAD

**Issue by TJPaik** [GUDHI/gudhi-devel#601]
Hello, I'm a student who is interested in TDA.
While using the gudhi, I found something strange. Please look at the code below.
```python
import gudhi

st = gudhi.SimplexTree()

st.insert([0, 1], filtration=2)
st.insert([2, 3], filtration=1)
st.insert([1, 2], filtration=3)

st.make_filtration_non_decreasing()

dgm = st.persistence(homology_coeff_field=2,)
for el in dgm:
    print(el)
print('-----------------')
st.extend_filtration()
dgms = st.extended_persistence(homology_coeff_field=2, )
print(dgms)
```
The result is : 
```
(0, (1.0, inf))
(0, (2.0, 3.0))
-----------------
[[], [], [(0, (1.0, 2.0))], []]
```
I think the ordinary part of extended persistent homology and the barcode of just persistent homology (excluding infinite barcode) should be the same, but the result is different. I think it's a bug if I didn't misunderstand the documentation.

**Comment by mglisse** [comment]
The documentation for [`extend_filtration()`](https://gudhi.inria.fr/python/latest/simplex_tree_ref.html#gudhi.SimplexTree.extend_filtration) says
> This function only uses the filtration values at the 0-dimensional simplices, and computes the extended persistence diagram induced by the lower-star filtration computed with these values.

The `st` on which you compute persistence is not a lower-star filtration, so it isn't surprising you get different results. Currently, your call to `st.make_filtration_non_decreasing()` has no effect. Did you mean to do `st.reset_filtration(-np.inf,min_dim=1)` before that?

**Comment by TJPaik** [comment]
@mglisse Thanks! I must have read it wrong. Thank you for fixing it. Let me close this issue. 👍 
I just added the make_filtration_non_decreasing part to make sure.
