### ISSUE TITLE
Documentation: unbalanced grouping in Simplex_tree.h

### ISSUE THREAD

**Issue by albert-github** [GUDHI/gudhi-devel#608]
When running doxygen on the sources of the project I get the warning:
```
src/Simplex_tree/include/gudhi/Simplex_tree.h:1781: warning: unbalanced grouping commands
```
this is due to the line:
```
/** @} */  // end defgroup simplex_tree
```
near the end of the file should be removed or whether a `\addtogroup` command analogous to e.g. src/Simplex_tree/include/gudhi/Simplex_tree/Simplex_tree_iterators.h
```
/* \addtogroup simplex_tree
 * ......
 * @{
 */
```
should be added.

**Comment by VincentRouvreau** [comment]
> near the end of the file should be removed or whether a `\addtogroup` command analogous to e.g. src/Simplex_tree/include/gudhi/Simplex_tree/Simplex_tree_iterators.h
> 
> ```
> /* \addtogroup simplex_tree
>  * ......
>  * @{
>  */
> ```

Isn't it the correct syntax like that:
```cmake
/** \addtogroup simplex_tree
 * ......
 * @{
 */
```
It isn't added to the group when `/* \addtogroup` (only one `*`)
