### ISSUE TITLE
Website: unreachable

### ISSUE THREAD

**Issue by albert-github** [GUDHI/gudhi-devel#622]
It looks like that the GUDHI website, https://gudhi.inria.fr/,  is unreachable (sometimes it looks like a page is reachable but this at that moment due to the fact that it is loaded from cache).

I also tried `ping` and `tracert`:
- `tracert https://gudhi.inria.fr`
  >Unable to resolve target system name https://gudhi.inria.fr.`

- `ping https://gudhi.inria.fr`
  > Ping request could not find host https://gudhi.inria.fr. Please check the name and try again.

**Comment by albert-github** [comment]
As far as I can see now the website is reachable again.

**Comment by mglisse** [comment]
Yes, a number of Inria servers didn't respond this week-end, I don't think it was anything specific to gudhi.
