### ISSUE TITLE
Cerificate problem for web site

### ISSUE THREAD

**Issue by albert-github** [GUDHI/gudhi-devel#625]
During a link check for the gudhi project (used: `https://gudhi.inria.fr`) I get messages like:
```
https://gudhi.inria.fr/
  Code: 500 Can't connect to gudhi.inria.fr:443 (certificate verify failed)
 To do: This is a server side problem. Check the URI.
```

would be nice when this could be fixed (Note: in internet browsers

**Comment by mglisse** [comment]
Indeed, `openssl s_client -showcerts -connect gudhi.inria.fr:443` complains (so do wget and any tools except browsers for some reason). It looks like the server only sends the final certificate and not the whole chain to a root certificate that would allow verifying it. @VincentRouvreau , I don't think we have any control on the server, can you open a ticket?

**Comment by mglisse** [comment]
Is it ok now?

**Comment by albert-github** [comment]
As far as I can see the problem as indicated is gone, thanks.

**Comment by VincentRouvreau** [comment]
Thanks for the report, I close the issue.
