### ISSUE TITLE
`std::iterator` deprecated in C++17

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#638]
https://github.com/GUDHI/gudhi-devel/blob/71beeb391cef793836e2d91598f9f942748edbb0/src/Bitmap_cubical_complex/include/gudhi/Bitmap_cubical_complex_base.h#L254

We should add the corresponding typedefs directly so we don't need to derive from it.

**Comment by VincentRouvreau** [comment]
If I have read carefully [this blog post](https://www.fluentcpp.com/2018/05/08/std-iterator-deprecated/), `std::iterator` will be deprecated in C++17, but it is not yet decided if it will be removed later (I didn't found any news about it).
The conclusion of this article is to explicitly define the 5 types required by an std::iterator when inheriting from it and to not use the default one.
Replace i.e. `class Filtration_simplex_iterator : std::iterator<std::input_iterator_tag, Simplex_handle>` with `class Filtration_simplex_iterator : std::iterator<std::input_iterator_tag, Simplex_handle, ptrdiff_t, Simplex_handle*, Simplex_handle&>`.

By the way, I tried to remove the inheritance and the code is still working. I am not sure this functionality is used...

@mglisse @Hind-M
* Do we remove the inheritance ?
* Or do we specify the 5 types of inheritance ?
* Something else ?

**Comment by mglisse** [comment]
```c++
class All_cells_iterator {
  typedef ... iterator_category;
  typedef ... reference;
  typedef ... pointer;
  typedef ... value_type;
  typedef ... reference_type;
  ...
}
```
Providing those types is needed to satisfy the concept of iterator. Just because some of them are not currently used doesn't mean we can remove them.

**Comment by VincentRouvreau** [comment]
> ```c++
> class All_cells_iterator {
>   typedef ... iterator_category;
>   typedef ... reference;
>   typedef ... pointer;
>   typedef ... value_type;
>   typedef ... reference_type;
>   ...
> }
> ```

These types must be public, that's it ?

**Comment by mglisse** [comment]
public. Private would be useless.
