### ISSUE TITLE
pip & macos arm64

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#682]
Follow-up to #533. We have a conda package for macos on arm64. With pip, we have a package for macos on x86_64, but not arm64. Arm64 will soon (< 2 years?) become more common than x86_64 as a macos platform, so I believe we should keep an issue open about adding a pip arm64 package (or making the existing one universal, or removing the existing x86_64 one if we think everybody uses conda on mac).

**Comment by VincentRouvreau** [comment]
@astamm Could you test the release candidate with `pip install gudhi==3.7.0rc1`, please ?

**Comment by VincentRouvreau** [comment]
> Import also works. Do you want me test whether I can actually use it ?

That should be ok. If import is working, the rest should be ok. Thank you @astamm 
I am closing the issue. Official release will follow
