### ISSUE TITLE
Correct way to build Doxygen documentation when building from git repo?

### ISSUE THREAD

**Issue by gspr** [GUDHI/gudhi-devel#683]
Hi. I'm struggling to correctly build the Doxygen documentation for the C++ API for GUDHI when building from git (i.e. not from the release tarballs). I suspect that this has to do with whole "user version" mechanism, but I'm not sure. If I configure with 
```
mkdir build
cd build
cmake -DUSER_VERSION_DIR=userversion ..
make user_version
```
followed by
```
make -C userversion doxygen
```
I get empty Doxygen documentation. If I change `INPUT` in src/Doxyfile.in to be blank instead of `@CMAKE_SOURCE_DIR@`, I do get generated Doxygen documentation, _but_ also for every C++ file that happens to be a part of the Python API.

It seems I'm fumbling blind here, so better to ask: what's the proper way to build the Doxygen documentation when building from a GUDHI git repo?

**Comment by VincentRouvreau** [comment]
Once you are in the `userversion` directory, you need to run cmake once again (maybe better in a build directory):
```bash
mkdir build
cd build
cmake -DUSER_VERSION_DIR=userversion ..
make user_version
cd userversion
mkdir build
cd build
cmake ..
make doxygen
```

If you want to speed up the documentation rendering, you can add `-DWITH_GUDHI_THIRD_PARTY=OFF` to both cmake calls as it won't try to detect third parties (not required by doxygen).

Historically, doxygen documentation were built in the developper version, and python documentation in the user version. Now both must be done from the user version as we explain how to build it in the documentation.

**Comment by gspr** [comment]
Thanks!
