### ISSUE TITLE
[C++] 3D periodic Alpha Complex - unable to construct a triangulation

### ISSUE THREAD

**Issue by ajouellette** [GUDHI/gudhi-devel#693]
This is tangentially related to #684. I'm trying to write a C++ function using 3D alpha complexes that can be wrapped in python. So, I take as input a 2D vector of doubles (3D coordinates of points) and then construct either a regular or periodic alpha complex based on those points. Here's an example of my code: https://gist.github.com/ajouellette/7ea976101bcba510bdff3ed7d4b37615, including a basic test where I compute the persistent homology of 10 random points inside a [-2,2] cube.

Using the regular non-periodic alpha complex works perfectly and I get what I expect, but when I try to use the periodic alpha complex, I get this error:
```
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Unable to construct a triangulation within a single periodic domain.
Aborted
```
Apparently constructing the alpha complex is failing, but I don't why. Is this a bug in my code or perhaps in the periodic alpha complex?

Thanks!

**Comment by VincentRouvreau** [comment]
I have the exact same test (just written differently) [written here](https://github.com/GUDHI/gudhi-devel/blob/fc8290b3ff3236ce88a5e6761dee3242ee1376a0/src/Alpha_complex/test/Periodic_alpha_complex_3d_unit_test.cpp#L70-L104).
The only thing that differs is the number of points.
If you set the number of points to 50 in your gist example, it works fine.

More details:
Behind the hood, we use CGAL Periodic triangulation and we need to check that the current triangulation would still be a triangulation in the 1-sheeted covering space with [is_triangulation_in_1_sheet](https://doc.cgal.org/latest/Periodic_3_triangulation_3/classCGAL_1_1Periodic__3__triangulation__3.html#aa9c1a5fa2b189d4578750e56b1fc0c2b).
I do not remember the exact reason, but this do not work if you do not have enough points in your bounding box.

Resolution:
Maybe we should had more details in the documentation.

**Comment by ajouellette** [comment]
Ok thanks!
I do not know much about the theory behind these calculations. Is there some place that explains more about why a periodic triangulation would not work? What is the significance of a 1-sheeted covering space?

I do agree that some extra details on this in the documentation could be useful.

**Comment by mglisse** [comment]
You can get most details by reading https://doc.cgal.org/latest/Periodic_3_triangulation_3/index.html and the papers it references.
In a nutshell, the resulting cell complex would not be a simplicial complex in that case (maybe there would be an edge connecting a vertex to itself, or 2 edges connecting the same pair of vertices, or something like that).
What we could produce is a simplicial complex built on top of 27 copies of the point set. That may not be what the user expects...
If the goal is only to compute persistence, we could compute it for this complex built on 27 copies, and I expect it is not too hard to deduce the persistence diagram for the cell complex. Or we would need a data structure for cell-complexes (or a suitable wrapper for the one in CGAL) so we can compute persistent homology directly on that.
Anyway, handling this case would require more work, and I don't expect it to be such a common case on real data.

**Comment by ajouellette** [comment]
Thanks for the explanation. I agree, it doesn't seem like this should be a common case in real data, it was just the small test case that confused me.
