### ISSUE TITLE
Empty diagram for plot_persistence_density

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#707]
Look at the last plot of https://gudhi.inria.fr/python/3.6.0/persistence_graphical_tools_user.html . It was ok in 3.5.0.

**Comment by VincentRouvreau** [comment]
The issue is no more present in [3.7.1](https://gudhi.inria.fr/python/3.7.1/persistence_graphical_tools_user.html) nor in [3.7.0](https://gudhi.inria.fr/python/3.7.0/persistence_graphical_tools_user.html)
