### ISSUE TITLE
[python] Unexpected behavior with Rips filtration when distance matrix identity entries are non-zero

### ISSUE THREAD

**Issue by tuanpham96** [GUDHI/gudhi-devel#723]
## Issue 

Recently when computing a distance matrix for a dataset I'm working on, I had forgotten to set the identity entries to 0. After I noticed the bug and corrected it, the results (a few steps after Rips filtration) came out differently. 

I initially thought that the fix wouldn't matter as I assume the filtration would possibly be done on the pairwise distances anyway, and self-loop values would be ignored. 

However, the results came out differently, and below is a minimal example with just `sklearn.make_circles`. 

## Minimal example

- First generate example data

  ``` python
  import numpy as np
  from sklearn.datasets import make_circles
  from sklearn import metrics
  import gudhi as gd
  from copy import deepcopy
  import matplotlib.pyplot as plt
  gd.persistence_graphical_tools._gudhi_matplotlib_use_tex=False
  
  # make data
  X, y = make_circles(n_samples=200, shuffle=True, noise=0.05, random_state=123, factor=0.4)
  
  # plot
  plt.scatter(X[:,0], X[:,1], c = y,s = 50)
  plt.axis('square')
  plt.show()
  ```
  ![gudhi-issue-example-data](https://user-images.githubusercontent.com/42875763/200147960-21a3a7dd-2d75-4cc7-8285-67b57ba0a33e.png)

- Construct the distance matrix, as well as the "wrong" ones with non-zero identity entries.

  ``` python
  # dist matrix
  D0 = metrics.euclidean_distances(X)
  
  # make non-zero for identity entries
  D1 = deepcopy(D0)
  D1[np.eye(len(D1)) > 0] = 0.5
  D2 = deepcopy(D0)
  D2[np.eye(len(D2)) > 0] = 1
  ```
- Compute & plot the persistence barcodes and diagrams
  
  ``` python
  # compute diagrams
  def get_dgm(D):
      skel = gd.RipsComplex(D, max_edge_length=3)
      spx_tree = skel.create_simplex_tree(max_dimension=3)
      dgm = spx_tree.persistence()    
      return dgm
  
  dgm_list = [get_dgm(D) for D in [D0, D1, D2]]
  
  # plot barcodes
  ttls = ['original distance', 'identity is 0.5', 'identity is 1']
  plt.figure(figsize=(18,10))
  for i, dgm in enumerate(dgm_list):
      ax1 = plt.subplot(2,3,i+1)
      gd.plot_persistence_barcode(dgm, axes=ax1)
      ax1.set_title(f'[{ttls[i]}] Barcode')
      
      plt.xlim(0, 3)    
      ax2 = plt.subplot(2,3,i+4)
      gd.plot_persistence_diagram(dgm, axes=ax2)
  ```

  ![gudhi-issue-example-diagrams](https://user-images.githubusercontent.com/42875763/200148049-f7a03da9-67aa-4f9e-965f-fef00f07e887.png)

## Observation

There are now **longer H0** bars and **later-born H1** bars, when the identity entries increase. 

Normally I would not care much, but it turned out the the "wrong" way resulted in better clustering down the line (I can expand on this if needed) than the correct way, which was quite perplexing to me. 

## System 

- Ubuntu 20.04.1
- python 3.10.5
- numpy 1.22.4
- scikit-learn 1.1.1 
- gudhi 3.6.0
- matplotlib 3.5.2

**Comment by mglisse** [comment]
```python
    skel = gd.RipsComplex(D, max_edge_length=3)
```
This interprets `D` as a list of points with coordinates, not as a distance matrix. Try instead
```python
    skel = gd.RipsComplex(distance_matrix=D, max_edge_length=3)
```
The [doc](https://gudhi.inria.fr/python/latest/rips_complex_ref.html#gudhi.RipsComplex.params.distance_matrix) is indeed not very clear about what happens if you do not name the arguments, but the definition is
```python
    def __init__(self, points=None, distance_matrix=None, max_edge_length=float('inf'), sparse=None):
```
It might have been clearer if we had made it
```python
    def __init__(self, *, points=None, distance_matrix=None, max_edge_length=float('inf'), sparse=None):
```
to forbid positional arguments for this function, you are not the first person to fall into this trap, but changing that now may break quite a bit of code, so I don't know.

**Comment by mglisse** [comment]
Cython has compiler directives like `binding`, `embedsignature`, etc that could help make the doc a bit clearer.

**Comment by tuanpham96** [comment]
Thank you @mglisse for pointing that out. Sorry I was careless. This is what came out when using keyword param with the above example, they came out the same:

```python
skel = gd.RipsComplex(distance_matrix=D, max_edge_length=2)
spx_tree = skel.create_simplex_tree(max_dimension=2)
```

![gudhi-issue-example-fix-with-kwargs-distmat](https://user-images.githubusercontent.com/42875763/200189436-a30b7b2e-5dc6-4977-a756-5d441fe14ef9.png)

----

I think it was confusing between the docstring and the tutorial(s). 

While the docstring indicates either 

- `points` and `max_edge_length`
- or just `distance_matrix`

One of the tutorials, e.g. [Tuto-GUDHI-persistence-diagrams](https://github.com/GUDHI/TDA-tutorial/blob/master/Tuto-GUDHI-persistence-diagrams.ipynb) one, in cell 4, mixes  `distance_matrix` and `max_edge_length` together:

```python
skeleton_protein0 = gd.RipsComplex(
    distance_matrix = D0.values, 
    max_edge_length = 0.8
) 
```

And I believe `max_edge_length` is still respected when `distance_matrix` is passed. For example, limit `max_edge_length=0.3`:

```python
skel = gd.RipsComplex(distance_matrix=D, max_edge_length=0.3)
spx_tree = skel.create_simplex_tree(max_dimension=2)
```

results in 

![gudhi-issue-example-distmat-with-maxlen](https://user-images.githubusercontent.com/42875763/200189522-fba25db2-7bd9-4474-a3eb-37674c47e733.png)

So technically the docstring should indicate arguments as:

- `points, [max_edge_length, [sparse]]`  -> assume  `distance_matrix=None`
- `distance_matrix,  [max_edge_length, [sparse]]` -> assume  `points=None`
----

> It might have been clearer if we had made it
> 
> ``` python
> def __init__(self, *, points=None, distance_matrix=None, max_edge_length=float('inf'), sparse=None):
> ```
>
> to forbid positional arguments for this function, you are not the first person to fall into this trap, but changing that now may break quite a bit of code, so I don't know.

In addition to having clearer docstring, how about also throwing a warning when user passes a symmetric (with some tolerance for numeric precision) matrix into `points`. E.g: 

```python
import warnings
def __init__(self, points=None, distance_matrix=None, max_edge_length=float('inf'), sparse=None, 
             point_warning=True, rtol_warning=1e-8, atol_warning=1e-10):
    
    if point_warning and type(points) is np.ndarray:
        suggest_mesg = 'If you intend to pass in a distance matrix, please indicate with keyword `distance_matrix=<input>`.\n' + \
                        'Silence this warning with `point_warning=False`.'
        if points.shape[0] == points.shape[1]:
            warnings.warn('The `points` input is a square matrix.\n' + suggest_mesg)
            if np.allclose(points, points.T, rtol=rtol_warning, atol=atol_warning):
                warnings.warn('The `points` input seems to be symmetric (with some tolerance).\n' + suggest_mesg)
    ...
 
```

----

Anyway, I can close this issue now. Thank you so much for pointing that out!

**Comment by mglisse** [comment]
> While the docstring indicates either
> 
>     * `points` and `max_edge_length`
>     * or just `distance_matrix`

That's not what it tries to say, but the rendering ends up confusing again. It says: max_edge_length, (points OR distance_matrix), but the rendering makes it look like (max_edge_length, points) OR distance_matrix. Moving max_edge_length next to sparse should already help a bit.

**Comment by tuanpham96** [comment]
Oh gotcha, your explanation clears up my confusion! And moving `max_edge_length` down would also help.
