### ISSUE TITLE
Subsampling dependency on CGAL

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#730]
https://gudhi.inria.fr/python/latest/point_cloud.html#subsampling says that gudhi.subsampling depends on CGAL+Eigen. But looking at the C++ code, only sparsify_point_set uses CGAL. It would be nice if the functions that do not use CGAL could be available when CGAL is missing, and the documentation needs to be more precise, since this has an impact on licensing.

**Comment by VincentRouvreau** [comment]
@mglisse Do you think we should rewrite the [c++ subsampling examples](https://gudhi.inria.fr/doc/latest/group__subsampling.html) without CGAL for `choose_n_farthest_points` and `pick_n_random_points` also ?
