### ISSUE TITLE
[Alpha_complex] Building a Delaunay triangulation (without filtration)

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#74]
I have seen several times people use Alpha_complex to build a Delaunay triangulation, and then ignore the filtration values (overwrite them with other values). IIRC, computing the filtration values is by far the most costly part of Alpha_complex, so this seems wasteful. It could be nice to have an option to say that we don't care about the filtration values.
An alternative way to resolve this would be to have a (simple, copy-pastable) example showing how to build a Simplex_tree representing the Delaunay triangulation of a point cloud, possibly using CGAL's python interface (or anything simple).

**Comment by VincentRouvreau** [comment]
What would be the best:
- Delaunay triangulation as a new module (Alpha complex could inherit from it)
- A new parameter in constructor (the desired filtration value) to trigger or not the computation. The Delaunay triangulation would have to be documented in Alpha complex this way.

**Comment by VincentRouvreau** [comment]
Closed by #165
