### ISSUE TITLE
python 3.11 wheels

### ISSUE THREAD

**Issue by baca790** [GUDHI/gudhi-devel#764]
Hi 
Would it be possible to release a python 3.11 wheel on pypi?
Python 3.11.1 is out now, so the major bugs will have been addressed and it is the current standard. 
Thanks and regards
Ben

**Comment by VincentRouvreau** [comment]
@baca790 Could you test the release candidate with `pip install gudhi==3.7.0rc1`, please ?

**Comment by baca790** [comment]
Yes all works great with python 3.11.1 as best I can tell. Thanks very much.

**Comment by VincentRouvreau** [comment]
Thank you @baca790 
I am closing the issue. Official release will follow
