### ISSUE TITLE
Compatibility with cython3

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#779]
(you can easily experiment with cython3 after `pip install -U --pre cython`)
Building the gudhi python plugin with cython 3.0.0a11, I get a number of errors like
> E       AttributeError: 'gudhi.simplex_tree.SimplexTree' object has no attribute '__is_defined'

Apparently cython changed the way it handles double underscores, and it now mangles those names in a way that breaks our use. If that works, I think we should switch to a single underscore, no need for the second one.

**Comment by mglisse** [comment]
This handling of `__` is a general Python thing: https://docs.python.org/3/tutorial/classes.html#private-variables
```
In [1]: class A:
   ...:     def __x(self):
   ...:         return True
   ...: a = A()
   ...: a.__x()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [1], line 5
      3         return True
      4 a = A()
----> 5 a.__x()

AttributeError: 'A' object has no attribute '__x'

In [2]: a._A__x()
Out[2]: True
```

**Comment by VincentRouvreau** [comment]
A reminder on this https://github.com/GUDHI/gudhi-devel/pull/777#discussion_r1061282173

**Comment by mglisse** [comment]
It seems that the only issue is using the functions `__is_defined()` and `__is_persistence_defined()` in tests. @VincentRouvreau , what do you prefer?
1. remove the assertions on those 2 functions from the tests
2. rename them so they start with a single underscore
3. on the day we switch to cython3, update the tests to `_SimplexTree__is_defined`, etc
4. other

I think I am in favor of option 2 (it is simple, compatible with both versions of cython, and I don't think the protection offered by the double underscore is that important here, but I could be wrong). We could also remove one underscore from `persistence_graphical_tools.__min_birth_max_death` while we are at it.

**Comment by mglisse** [comment]
Cython3 is now out, and at least one macosx CI job already uses it (and fails).
