### ISSUE TITLE
introduction.rst not installed properly by pip

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#808]
`introduction.rst` installation should be reworked considering [this documentation](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/) as this file is sometimes installed in `~/.local `.
File copy could also be avoided and `long_description` could be filled by CMake reading `introduction.rst`.

**Comment by mglisse** [comment]
Apparently we can also specify things in pyproject.toml (https://packaging.python.org/en/latest/specifications/declaring-project-metadata/#readme).
