### ISSUE TITLE
alpha persistence diagrams scaling

### ISSUE THREAD

**Issue by nihell** [GUDHI/gudhi-devel#811]
Hi, I'm running gudhi version 3.7.1 on Pop!_OS 22.04.
Consider the following code:
`def alpha_1d_dgm_from_points(X):
    ac = gd.AlphaComplex(points = X)
    st = ac.create_simplex_tree()
    st.compute_persistence()
    pd = st.persistence_intervals_in_dimension(1)
    return pd

rng = default_rng(0)
X = rng.uniform(0,1,(10,3))

print(alpha_1d_dgm_from_points(X))
print(alpha_1d_dgm_from_points(X*100))`

Expected behavior: the persistence diagrams are scaled by a factor of 100
Observed behavior: the persistence diagrams are scaled by a factor of 100*100

More generally, the alpha persistence diagrams seem to scale quadraticly, and not linearly.
Note that this leads to lack of comparability with Rips filtrations.

More dramatically, you can generate two point clouds with fixed Hausdorff distance, but arbitrary large bottleneck distance of their persistence diagrams. This is impossible by the stability theorem.

**Comment by mglisse** [comment]
See #771 for instance.

**Comment by mglisse** [comment]
Let me close this issue, we are already tracking this in #771. In the mean time, people can apply sqrt to the filtration values of the complex, or to the output persistence diagram. Note that to compare with the Rips, you may also need to scale by a factor of 2.
