### ISSUE TITLE
path to how_to_cite_gudhi.bib

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#826]
https://github.com/GUDHI/gudhi-devel/blob/f41c856d3ea0066fe0bcec2121506a7ca11301cc/src/Doxyfile.in#L703

looks for this file in one place, but
https://github.com/GUDHI/gudhi-devel/blob/f41c856d3ea0066fe0bcec2121506a7ca11301cc/src/cmake/modules/GUDHI_user_version_target.cmake#L19
puts it in a different place.
When I build the doc (and more) from a subdirectory with `cmake .. -DWITH_GUDHI_PYTHON=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_GUDHI_EXAMPLE=ON -DWITH_GUDHI_BENCHMARK=ON && cmake --build . -j16 -t doxygen -t all`, I see in doxygen.log
> error: bib file /home/glisse/repos/gudhi/biblio/how_to_cite_gudhi.bib not found!

and indeed Doxyfile contains this wrong path.

**Comment by VincentRouvreau** [comment]
I suppose this is a "developer" and not a "user" version ?

This is like that since #484 where I "homogenized" python and c++ documentation rendering for the "user" version. Before this PR, python was requiring "user" version and c++ was requiring "developer" version.

**Comment by mglisse** [comment]
Ah, so doxygen works only on the user version, but the C++ tests still require the developer version?

**Comment by mglisse** [comment]
#612 may be related.

**Comment by mglisse** [comment]
The last commit of #1102 may have fixed this.
