### ISSUE TITLE
Recommend `-DCMAKE_BUILD_TYPE=Release`

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#87]
In the documentation (say python installation), we show commands to build gudhi, and in particular we show `cmake ..`. Doing this, we get the "CGAL performance notice" which recommends adding `-DCMAKE_BUILD_TYPE=Release`. Should we add this argument in the doc? Or if for some reason it does not apply, should we disable the warning with `CGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE=TRUE`?

**Comment by VincentRouvreau** [comment]
Does it really affect CGAL performances if we do not set `CMAKE_BUILD_TYPE` ?
(or if we set `CGAL_DO_NOT_WARN_ABOUT_CMAKE_BUILD_TYPE=TRUE`)

**Comment by VincentRouvreau** [comment]
Closed by #384
