### ISSUE TITLE
make install and python plugins

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#89]
Running `make install` does not seem to install the python stuff here. I do get some messages though:

> /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'install_requires'
>   warnings.warn(msg)
> /usr/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'setup_requires'
>   warnings.warn(msg)
> error: package directory 'gudhi' does not exist

Maybe if we create that directory 'gudhi' then it installs things there?

**Comment by VincentRouvreau** [comment]
Warnings fixed on dcbdaa0dc00eb069d1a13575f22c0a2f7d63dcc8
`make install` may requires super user privileges.

**Comment by VincentRouvreau** [comment]
@mglisse Could you try again with gudhi 3.0.0, please ?
It shall be fixed.

**Comment by mglisse** [comment]
I gave `-DCMAKE_INSTALL_PREFIX=/tmp/i` to cmake, hoping that it would install everything there. It does for the C++ stuff. But for python
> The installation directory you specified (via --install-dir, --prefix, or the distutils default setting) was:
> 
>     /usr/local/lib/python3.7/dist-packages/

and it fails because it doesn't have permission. Of course I could give it permission, but that's not my goal, I passed CMAKE_INSTALL_PREFIX for a reason. Is there a separate variable to indicate where I want the python stuff to go?

**Comment by VincentRouvreau** [comment]
Ok, now I get it.
You were expecting `make install` to use `python setup.py install --prefix=/tmp/i` as explained [here](https://docs.python.org/3/install/#alternate-installation-unix-the-prefix-scheme) ?

**Comment by mglisse** [comment]
> You were expecting `make install` to use `python setup.py install --prefix=/tmp/i` as explained [here](https://docs.python.org/3/install/#alternate-installation-unix-the-prefix-scheme) ?

Yes. I admit that it is probably not what most users want, although they probably want it in their HOME rather than the system, I see I have ~/.local/lib/python3.7/site-packages/, is that reserved for pip?.

**Comment by VincentRouvreau** [comment]
Work around on #153
