### ISSUE TITLE
Simplex_tree number of simplices per dimension

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#894]
We could add a function that returns a vector `v` where `v[i]` says how many simplices of dimension `i` we have in the complex. This can be a bit more efficient than a user iterating on all simplices and incrementing the right element of `v` because we would know the dimension of the simplex already instead of recomputing it.

Actually, I was also considering at some point a function `for_each_simplex_with_dimension` which would take a functor `f` and call `f(s,d)` for each simplex s of dimension d, which would make this easy, but adding more for_each-type functions (because our iterators are too heavy) may be a different issue.

**Comment by VincentRouvreau** [comment]
Considering this, #183 would become obsolete, no ? (another to do it)

**Comment by mglisse** [comment]
> Considering this, #183 would become obsolete, no ? (another way to do it)

Not really. If I ask for a range of all edges, I don't want to go through all the tetrahedra just to ignore them afterwards.
