### ISSUE TITLE
Macos options

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#899]
Instead of an explicit `-mmacosx-version-min=10.14` in src/python/CMakeLists.txt and `ARCHFLAGS: "-arch arm64 -arch x86_64"` in .github/workflows/pip-packaging-osx.yml, we should investigate using CMAKE_OSX_DEPLOYMENT_TARGET and CMAKE_OSX_ARCHITECTURES. Maybe we already did and ended up with what we have because of the complicated cmake+setuptools mix.

The current github action works if we remove `-mmacosx-version-min=10.14`, but I didn't check the azure one.

This is mostly a reminder that the macos situation is currently messy.

**Comment by VincentRouvreau** [comment]
I did some tests on #945 
`CMAKE_OSX_ARCHITECTURES` is never set...
`CMAKE_OSX_DEPLOYMENT_TARGET` is set to `12.6` in Azure OSX and `11.7` in pip build OSx on CI.

For pip build `CMAKE_OSX_DEPLOYMENT_TARGET` is set to `11.7`, thanks to environment variable `MACOSX_DEPLOYMENT_TARGET` (as explained in [CMake documentation](https://cmake.org/cmake/help/latest/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html))

Maybe we could just replace https://github.com/GUDHI/gudhi-devel/blob/f1b7e56bec0fe88090324c34b9a2cede04d4e47b/src/python/CMakeLists.txt#L258-L259 with:
```
      set(GUDHI_PYTHON_EXTRA_COMPILE_ARGS "${GUDHI_PYTHON_EXTRA_COMPILE_ARGS}'-mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}', ")
      set(GUDHI_PYTHON_EXTRA_LINK_ARGS "${GUDHI_PYTHON_EXTRA_LINK_ARGS}'-mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}', ")
```

**Comment by mglisse** [comment]
> `CMAKE_OSX_ARCHITECTURES` is never set...

I was thinking of it as a replacement for ARCHFLAGS in pip-build-osx.yml.

Ideally we would not have any mention of `-mmacosx-version-min=` in our CMakeLists.txt, since this is more part of packaging. CMake normally already adds suitable `-mmacosx-version-min` flags, but it doesn't look like we copy all the flags from cmake to setup.py, only some. Did you try adding CMAKE_CXX_FLAGS (or similar) to the arguments we send to setup.py (and similar for linking)? Your proposal with `-mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}` makes sense. I think gudhi will fail to build if the version is too low, I don't know if we should forcibly increase it in that case, or leave that responsibility to whoever is compiling.

**Comment by VincentRouvreau** [comment]
> Ideally we would not have any mention of `-mmacosx-version-min=` in our CMakeLists.txt, since this is more part of packaging. CMake normally already adds suitable `-mmacosx-version-min` flags, but it doesn't look like we copy all the flags from cmake to setup.py, only some. Did you try adding CMAKE_CXX_FLAGS (or similar) to the arguments we send to setup.py (and similar for linking)?

I added some traces, but for [pip OSX](https://github.com/GUDHI/gudhi-devel/actions/runs/6106076167/job/16570562628?pr=945) and [Azure OSX](https://dev.azure.com/GUDHI/gudhi-devel/_build/results?buildId=2501&view=logs&jobId=cf796865-97b7-5cd1-be8e-6e00ce4fd8cf&j=cf796865-97b7-5cd1-be8e-6e00ce4fd8cf&t=d5062407-4aaa-5468-7238-c199647c44e2), I have:
```txt
++ CMAKE_CXX_FLAGS=  -Wall -pedantic
++ CMAKE_CXX_FLAGS_RELEASE=  -O3 -DNDEBUG
++ LINK_FLAGS= 
++ CMAKE_EXE_LINKER_FLAGS= 
++ CMAKE_SHARED_LINKER_FLAGS= 
++ CMAKE_MODULE_LINKER_FLAGS_RELEASE= 
```
Maybe I missed some variables but after a quick look inside CMakeCache.txt, I do not see good candidates :cry: 

> Your proposal with `-mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}` makes sense. I think gudhi will fail to build if the version is too low, I don't know if we should forcibly increase it in that case, or leave that responsibility to whoever is compiling.

Ok, I will propose a PR with this fix

**Comment by mglisse** [comment]
> Maybe I missed some variables but after a quick look inside CMakeCache.txt, I do not see good candidates 😢

Ah, cmake adds `-mmacosx-version-min=*` directly to the command instead of adding it to some variable used in the command? That's inconvenient...
