### ISSUE TITLE
make clean and python

### ISSUE THREAD

**Issue by mglisse** [GUDHI/gudhi-devel#90]
`make clean` does not remove the cython plugins. Not a priority, it just confused me a bit when experimenting.

**Comment by VincentRouvreau** [comment]
`make python` is a [cmake custom target](https://cmake.org/cmake/help/latest/command/add_custom_target.html) that does a `python setup.py build_ext --inplace`.
Unfortunately, cmake has no mecanism to add a custom target to the clean target, cf. https://gitlab.kitware.com/cmake/cmake/issues/16358
I could do a new cmake custom target, `make clean_python` for instance, that does a `python setup.py clean --all`.

**Comment by mglisse** [comment]
Adding `${Cython_BINARY_DIR}` to `ADDITIONAL_CLEAN_FILES` looks like it might help, but it didn't in a quick test (that I most likely botched anyway).

**Comment by VincentRouvreau** [comment]
Work around on #153
