### ISSUE TITLE
RipsComplex computation incorrect when distance matrix does not satsify triangle inequality

### ISSUE THREAD

**Issue by longyuxi** [GUDHI/gudhi-devel#913]
The calculation of RipsComplex() is incorrect when the distance matrix does not satisfy triangle inequality. I am not sure if the triangle inequality is an assumption made when developing this package, but this should at least be made clear in the documentation.

Here is an example code:

```
import numpy as np
import gudhi
from scipy.spatial.distance import cdist

points = [[1, 1, 0], [1, 0, 0], [0, 1, 1], [0, 0, 1]]


def distance_function(x, y):
    if np.array_equal(x, y):
        return 0
    else:
        if np.abs(x[2] - y[2]) <= 0.5:
            return np.inf
        else:
            return np.linalg.norm(x[:2] - y[:2])


distance_matrix = cdist(points, points, metric=distance_function)

print(distance_matrix)

#array([[0.        ,        inf, 1.        , 1.41421356],
#       [       inf, 0.        , 1.41421356, 1.        ],
#       [1.        , 1.41421356, 0.        ,        inf],
#       [1.41421356, 1.        ,        inf, 0.        ]])

rips_complex = gudhi.RipsComplex(distance_matrix=distance_matrix, max_edge_length=2.0)

simplex_tree = rips_complex.create_simplex_tree(max_dimension=2)

print(simplex_tree.persistence())
#[(0, (0.0, inf)),
# (0, (0.0, 1.4142135623730951)),
# (0, (0.0, 1.0)),
# (0, (0.0, 1.0))]
```

In this case, there should exist a 1D hole with (birth, death) parameters (1.414. inf), but it is not in the program output.

**Comment by mglisse** [comment]
Try `simplex_tree.persistence(persistence_dim_max=True)`. There are no triangles, so without this option we only compute persistence in dimension 0. Yes, this is very misleading. In #691 we are adding a new interface where we explicitly say which dimensions we want. This issue can serve as a reminder to consider if we could change the arguments of `SimplexTree.compute_persistence` to make them less error-prone.
