### ISSUE TITLE
Error in BettiCurve fit/fit_transform function 

### ISSUE THREAD

**Issue by Matthew-Vandergrift** [GUDHI/gudhi-devel#923]
When using the BettiCurve function this error will always appear: AttributeError: 'list' object has no attribute 'flatten'. I am not sure what the solution is, since the error will occur seemingly always. When the example code in the document here : https://gudhi.inria.fr/python/latest/representations.html#gudhi.representations.vector_methods.BettiCurve is run the error still occurs. If anyone know of a solution, please let me know thanks!

**Comment by mglisse** [comment]
Well, not **always** since our tests pass. Could you provide a very small complete example that fails? Both `fit` and `transform` expect a list of numpy arrays, are you giving them a list of lists instead? We could (and probably should) make the code more permissive by replacing `xxx.flatten(...)` with `np.flatten(x, ...)` though, or something similar.

**Comment by Matthew-Vandergrift** [comment]
Thank you for the response. My issue is that from what I know the persistence function returns a list, hence the error is occurring. This is the example I am currently working with,  
eps = 1
rips_complex = gudhi.RipsComplex(distance_matrix=dist_matrix, max_edge_length=eps)
simplex_tree = rips_complex.create_simplex_tree(max_dimension=1)
pd = simplex_tree.persistence(homology_coeff_field=2, min_persistence=0)
bc = BettiCurve(resolution=None, predefined_grid=None)
bettis = bc.fit_transform([pd])

Should I simply convert pd into a numpy array? Is there a function which returns a persistence diagram as a numpy array, I have been looking into the documentation but cannot find such a function? Additionally if there is any example of code which can plot a Betti curve using GUDHI it might be able to answer my question. 

Thank you so much for your time, and answer!

**Comment by mglisse** [comment]
Ah, ok, different problem. `persistence` returns the full diagram in some old inconvenient format. What the representation classes want to work with is the output of [`persistence_intervals_in_dimension`](https://gudhi.inria.fr/python/latest/simplex_tree_ref.html#gudhi.SimplexTree.persistence_intervals_in_dimension).

Sorry, having 2 different ways to represent diagrams is bound to lead to trouble and confusion. For Rips in particular, we will soon add a class RipsPersistence (or a similar name) with a sklearn-like interface, and that returns diagrams directly in a format suitable for BettiCurve.

**Comment by Matthew-Vandergrift** [comment]
Thank you so much for the help! My mistake was confusing the two persistence functions but it makes perfect sense with the explanation really appreciate it.
