### ISSUE TITLE
[Simplex tree] Avoid final substraction in dimension computation

### ISSUE THREAD

**Issue by VincentRouvreau** [GUDHI/gudhi-devel#972]
I wonder why we don't initialize `dim` to -1 instead of 0 to avoid this final subtraction, but it isn't new in this PR.

_Originally posted by @mglisse in https://github.com/GUDHI/gudhi-devel/pull/886#discussion_r1333557810_

**Comment by mglisse** [comment]
It looks like this was done in #886.
