### ISSUE TITLE
[Cover Complex] Make KeplerMapper a Python function

### ISSUE THREAD

**Issue by MathieuCarriere** [GUDHI/gudhi-devel#991]
So far, the interactive visualization of cover complexes must be done with a command line, eg 
`!python ./utils/KeplerMapperVisuFromTxtFile.py -f human.txt` 
Instead, it would be better to call it with something like 
`CoverComplex().save_to_html_with_KeplerMapper()`.

**Comment by VincentRouvreau** [comment]
Fixed by #997
